### ISSUE TITLE
Not Found

### ISSUE THREAD

**Issue by Vasago** [Shadez/wowarmory#10]
All *xml files are not found on my copy (search.xml etc) ... I am using php5+apache2+mysql+xml-parser
Debian linux 32bit + Trinity 333a + patch + sql in armory so where is my problem? Thank you.

**Comment by Shadez** [comment]
You need to enable mod_rewrite (Apache module) and extract all .htaccess files from htaccess.zip.

**Comment by Vasago** [comment]
Ok have it thanks - fixed closed

**Comment by DGdev91** [comment]
Same problem, but mod_rewrite is enabled on my server (i used webmin to activate it)
I have to install some extra package?
