### ISSUE TITLE
Search is not using Mangos or Trinity

### ISSUE THREAD

**Issue by Der-WU** [Shadez/wowarmory#101]
The search of teh Armory did search on account for gmlevel.
But on trinity it´s on account_access.
I have change line account to account_acess, but shadez should do that conf is checking and use mangos or trinity.
it fix the gmlevel error on debug when search is used on a trinity server. ;)

sorry for my bad english. 

Greatz WuChEn

**Comment by Shadez** [comment]
Thank you, should be fixed after [423] revision.
