### ISSUE TITLE
Newest Patch File.

### ISSUE THREAD

**Issue by Der-WU** [Shadez/wowarmory#103]
I have try your new Patch file.
Got this error on compile:

[ 11%] Building CXX object src/server/game/CMakeFiles/game.dir/Entities/Item/Item.cpp.o
/home/wuwow/trinitycore/src/server/game/Entities/Item/Item.cpp: In static member function 'static Item\* Item::CreateItem(uint32, uint32, const Player_)':
/home/wuwow/trinitycore/src/server/game/Entities/Item/Item.cpp:1022: error: 'pItem' was not declared in this scope
make[2]: *_\* [src/server/game/CMakeFiles/game.dir/Entities/Item/Item.cpp.o] Fehler 1
make[1]: **\* [src/server/game/CMakeFiles/game.dir/all] Fehler 2
make: **\* [all] Fehler 2

Greatz WuChEn

**Comment by Shadez** [comment]
Should be fixed in [425], thank you!

**Comment by duergar85** [comment]
When I apply the wowarmory_patch.patch patch, it gives me this error:
patch: ***\* malformed patch at line 49:
As soon as I removed the white lines between the + starting lines, I fixed this problem.
I'm on Kubuntu Linux 10.10 with patch 2.6

Thanks for your Armory, it's very good!

duergar85
