### ISSUE TITLE
Trinity Core

### ISSUE THREAD

**Issue by duergar85** [Shadez/wowarmory#104]
I modified the TC arena patch to make it compile in the 04ce0858ce41 revision of Trinity Core. It compiles, I don't know if it works tho.
I upped the file here -> http://www.yourfilehost.com/media.php?cat=other&file=wowarmory_arena_chart_2.patch
Hope this will be useful for someone or for the project.

Thanks,
duergar85

**Comment by Shadez** [comment]
In [427], thank you very much!
