### ISSUE TITLE
GM is not showed on Armory

### ISSUE THREAD

**Issue by Der-WU** [Shadez/wowarmory#105]
Hey everybode.

My GM-Level is 4.
My User-Level is 11.

Config is set to:
$ArmoryConfig['settings']['minlevel']         = 10;
$ArmoryConfig['settings']['minGmLevelToShow'] = 3;

But if i search for my Character, not found.

Log:
DEBUG [28-12-2010 11:20:07]: Characters::BuildCharacter : Player 1 (Wuchen) is not allowed to be displayed in Armory (GM level restriction or has low level)!

If i delete my GM rights, it works. 
Whats wrong?

Greatz WuChEn
## 

Tested with GMLevel 3, works too.
Only GM Level 4 is not showed.

Greatz WuChEn

---

Change:
$ArmoryConfig['settings']['minGmLevelToShow'] = 4;
Works fine, but 4 is not a "official" Value :D

Greatz WuChEn

**Comment by duergar85** [comment]
I think that the settings from 0 to 3 are for Mangos GM-levels. Trinity Core, for instance, supports a GM-level of 0 to 4 (4 are Admins). Normally I set that variable to 4 and it simply works.

**Comment by Shadez** [comment]
Yes, duergar85's right - 0-3 are MaNGOS' acces levels. Just set $ArmoryConfig['settings']['minGmLevelToShow'] value to any GM level you have.

**Comment by Shadez** [comment]
[428] - Note about it was added to config.
