### ISSUE TITLE
Display problem of Umlauts in instance names

### ISSUE THREAD

**Issue by predator558** [Shadez/wowarmory#108]
I got a problem with umlauts in instance names in search result.

for e.g. he write &amp;#252; instead of &#252;

Am i the only one with this problem?

**Comment by sonyc** [comment]
check armory_instance_template

**Comment by predator558** [comment]
They are right in the db, but on the page they will be displayed wrong, because the & willl be converted to html code.

**Comment by sonyc** [comment]
okay I'm not the problem 

I'm sorry for my english
I can not English

**Comment by predator558** [comment]
Sorry but your answer don't help me :-)
i also can speak german if you from germany.

**Comment by sonyc** [comment]
Super nen link wäre nice von deiner armory seite 
dann schau ich mal

**Comment by predator558** [comment]
Ok schreib ich dir gleich ich installiere grad die Db neu.
Wie lang bist du ca noch online?
achja und danke für deine Hilfe.

**Comment by sonyc** [comment]
noch ca 1-2 Stunden

**Comment by predator558** [comment]
So now i test it on 3 different machines and all do the same the write umlauts wrong because the & will be converted, so i think its a mistake in a script.
my db collation is utf8_general_ci and the connection encoding is UTF8 too.
i tried latin1 but changed nothing.

Ich habe es jetzt auch 3 verschiedenen Rechnern getestet und alle tun das selbe, sie zeigen Umlaute nicht an weil das & zeichen in html code umgewandelt wird.
Also wird es wohl ein Skript fehler sein.
Meine db Kollation ist utf8_general_ci und die Verbinduns codierung ist UTF8,
ich habe auch latin1 probiert, ändert aber leider nichts am problem.

**Comment by Shadez** [comment]
This should be fixed after <a href="https://github.com/Shadez/wowarmory/commit/7de14b3d0f73bab27d788e4a54e2dab9dabaa5cb">[447]</a> revision. Please, check it and report back.
Thank you.

**Comment by predator558** [comment]
Hey Shadez,
thanks, great work.
