### ISSUE TITLE
patch error

### ISSUE THREAD

**Issue by sprokopiev** [Shadez/wowarmory#109]
I apply two patches but error apears:
Sorry for my bad English , I am Bulgarian.

[  9%] Building CXX object src/server/game/CMakeFiles/game.dir/Battlegrounds/Battleground.cpp.o
/home/darkvader/install/TrinityCore/src/server/game/Battlegrounds/Battleground.cpp: In member function 'virtual void Battleground::UpdatePlayerScore(Player_, uint32, uint32, bool)':
/home/darkvader/install/TrinityCore/src/server/game/Battlegrounds/Battleground.cpp:1431: error: 'SCORE_DAMAGE_TAKEN' was not declared in this scope
/home/darkvader/install/TrinityCore/src/server/game/Battlegrounds/Battleground.cpp:1434: error: 'SCORE_HEALING_TAKEN' was not declared in this scope
gmake[2]: *_\* [src/server/game/CMakeFiles/game.dir/Battlegrounds/Battleground.cpp.o] Error 1
gmake[1]: **\* [src/server/game/CMakeFiles/game.dir/all] Error 2
gmake: **\* [all] Error 2

**Comment by Shadez** [comment]
Try to 
`git reset --hard HEAD`

then
`git clean -f -x -d`
and then re-apply patches again because patches are correct (but anyway, I'll check it).

**Comment by sprokopiev** [comment]
yes it work now.10x
