### ISSUE TITLE
Bad layout

### ISSUE THREAD

**Issue by Vasago** [Shadez/wowarmory#11]
As you can see in firefox it is displayed in wrong way 
[URL=http://img688.imageshack.us/i/armory.png/][IMG]http://img688.imageshack.us/img688/1174/armory.th.png[/IMG][/URL]

Information what i am using are in previous report. Thx

**Comment by amsjunior1** [comment]
you need to install images.... go to downlaods

**Comment by Vasago** [comment]
There are only icons ... As you can see i am missing logo and basic layout images ...

**Comment by amsjunior1** [comment]
wow-icons_r142_RC1_v333a.7z take this from download

after upload and unzip  in folder site.
see install head me

**Comment by Vasago** [comment]
I unziped all from this zip to wow-icons/_images/ and still no change ...

**Comment by amsjunior1** [comment]
if you use linux make permission 777 to folder CACHE and try again

**Comment by Vasago** [comment]
Folder chmoded to 777 and still no change ...

**Comment by Vasago** [comment]
http://yfrog.com/f1armory2p here is the character view - except errors pictures are there but no logo and still the same front page ... What am I doing wrong?

**Comment by Vasago** [comment]
I have found a problem if it when i set in config option "en_us" it doesnt show the pictures right "en_gb" works fine.

**Comment by Shadez** [comment]
Thank you, i'll add images & css files for enUs locale.
