### ISSUE TITLE
[TC]Talentos Paladín es_es

### ISSUE THREAD

**Issue by Gooyeth** [Shadez/wowarmory#112]
(Disculpen que haga el reporte en español sé poco inglés, si alguien me lo traduce se lo agradecería demasiado)

Los talentos de Paladin para es_es no se muestran, una imagen:
http://img248.imageshack.us/img248/1640/esesz.png

En cambio en la en_gb si se muestran:
http://img585.imageshack.us/img585/2558/engb.png

Los talentos no se muestran en la calculadora de talentos ni en el perfil de personaje

Creo que ese es mi reporte, gracias por todo ^^

**Comment by Shadez** [comment]
Fixed in <a href="https://github.com/Shadez/wowarmory/commit/c0b599c7483b70f607416ae3ac0d302ab3dd5c8c">[452]</a>, thank you!

**Comment by Gooyeth** [comment]
Gracias :D
