### ISSUE TITLE
Trinity 3.3.5 no items shown in char-sheet

### ISSUE THREAD

**Issue by xseanx** [Shadez/wowarmory#113]
Trinity-Server 3.3.5 (12340)
Armory revision: 451
DB Version: armory_r434

my problem: the character-sheet fully loads, 3D view too, but equipped item slots remain empty.
http://img831.imageshack.us/img831/3360/screencz.jpg

and except these no debug info in log...
ERROR [16-01-2011 11:09:17]: Characters::GetCharacterItemInfo : slot 16 is empty (nothing equipped?)
ERROR [16-01-2011 11:09:17]: Characters::GetCharacterItemInfo : slot 18 is empty (nothing equipped?)
DEBUG [16-01-2011 11:09:18]: Characters::BuildCharacter : all correct, player Sean (GUID: 2, raceID: 1, classID: 1, level: 80) loaded, class has been initialized.

**Comment by Shadez** [comment]
Is this happends on latest revision too?

**Comment by xseanx** [comment]
still the same problem.
