### ISSUE TITLE
Characters

### ISSUE THREAD

**Issue by Subv** [Shadez/wowarmory#114]
The armory shows the characters in the search, but when you click on the link, it does not show it, it says: 
File Not Found,  
This character profile could not be displayed, possibly for one of the following reasons:
The character has been inactive for an extended period of time.
The character name was spelled incorrectly.
The profile is temporarily unavailable while the character is in the midst of a process such as a realm transfer or faction change.
Characters that have been deleted are no longer available on the Armory.

**Comment by Jildor** [comment]
Connect with player and logout.

Search player name and .... works

**Comment by Subv** [comment]
i will try it and comment what happened

**Comment by Subv** [comment]
That didnt work, please help me

**Comment by xseanx** [comment]
using trinity? core patched?
in characters-db armory_character_stats-table empty?

or just try .save ingame...

**Comment by Subv** [comment]
i havent patched the core, and armory_character_stats is empty

**Comment by xseanx** [comment]
and your are using trinity?
so look ...\tools\trinity_core\Readme.txt
apply characters_patch.sql in the characters-database of trinity-core,
and rebuild your core with the changes listet in "wowarmory_arena_chart.patch" and "wowarmory_patch.patch". (TortoiseHG would make it much easier btw...)

**Comment by Shadez** [comment]
Please, read installation info carefully. Closed.
