### ISSUE TITLE
Custom items

### ISSUE THREAD

**Issue by Subv** [Shadez/wowarmory#118]
well, my custom items arent showing correctly in the armory, i mean the page loads, but in the layout, where the stats of the item should be, is empty, the sellprice and buyprice are displayed correctly, thanks

**Comment by Shadez** [comment]
Try to open item-tooltip.xml?i=item_id - may be there's some error message?

**Comment by Subv** [comment]
with item-tooltip.xml?i=item_id it says:
 This page contains the following errors:
error on line 2 at column 1: Extra content at the end of the document
Below is a rendering of the page up to the first error.

but below is empty

and in view source says:
<br /> 
<b>Notice</b>:  Undefined offset: 0 in <b>C:\Xampp\xampp\htdocs\Armory\wowarmory\includes\classes\class.items.php</b> on line <b>1797</b><br /> 
<br /> 
<b>Notice</b>:  Undefined offset: 0 in <b>C:\Xampp\xampp\htdocs\Armory\wowarmory\includes\classes\class.items.php</b> on line <b>1798</b><br /> 
<br /> 
<b>Notice</b>:  Undefined offset: 0 in <b>C:\Xampp\xampp\htdocs\Armory\wowarmory\includes\classes\class.items.php</b> on line <b>1820</b><br /> 
<br /> 
<b>Notice</b>:  Undefined offset: 0 in <b>C:\Xampp\xampp\htdocs\Armory\wowarmory\includes\classes\class.items.php</b> on line <b>1821</b><br /> 
<br /> 
<b>Notice</b>:  Undefined offset: 0 in <b>C:\Xampp\xampp\htdocs\Armory\wowarmory\includes\classes\class.items.php</b> on line <b>1822</b><br /> 
<br /> 
<b>Notice</b>:  Undefined offset: 1 in <b>C:\Xampp\xampp\htdocs\Armory\wowarmory\includes\classes\class.items.php</b> on line <b>1820</b><br /> 
<br /> 
<b>Notice</b>:  Undefined offset: 1 in <b>C:\Xampp\xampp\htdocs\Armory\wowarmory\includes\classes\class.items.php</b> on line <b>1821</b><br /> 
<br /> 
<b>Notice</b>:  Undefined offset: 1 in <b>C:\Xampp\xampp\htdocs\Armory\wowarmory\includes\classes\class.items.php</b> on line <b>1822</b><br /> 
<?xml version="1.0" encoding="UTF-8"?> 
<?xml-stylesheet type="text/xsl" href="_layout/items/tooltip.xsl"?><page globalSearch="1" lang="es_es" requestUrl="item-tooltip.xml"><itemTooltips><itemTooltip><id>65003</id><name>Reclaimed Ashkandi, Greatsword of the Brotherhood</name><icon></icon><heroic>1</heroic><overallQualityId>4</overallQualityId><bonding>1</bonding><maxCount>1</maxCount><classId>2</classId><equipData><inventoryType>17</inventoryType><subclassName>Espada</subclassName></equipData><damageData><damage><type>0</type><min>0</min><max>0</max></damage><speed>3.8</speed></damageData><bonusStrength>385</bonusStrength><bonusStamina>578</bonusStamina><bonusCritRating>257</bonusCritRating><bonusHitRating>257</bonusHitRating><armor></armor><socketData/><durability current="120" max="120"/><requiredLevel>85</requiredLevel><itemLevel>372</itemLevel><spellData/><itemSource value="sourceType.vendor"/></itemTooltip></itemTooltips></page> 

Looks like this error is with all the weapons

**Comment by Shadez** [comment]
Can you provide SQL dump for your custom item, please?
