### ISSUE TITLE
bad select in trinitycore

### ISSUE THREAD

**Issue by SignFinder** [Shadez/wowarmory#119]
<strong>DEBUG</strong> [19-01-2011 21:17:45]: ArmoryDatabaseHandler::_query : unable to execute SQL query (SELECT `current_rank` FROM `character_talent` WHERE `guid`=849247 AND `talent_id`=2020 AND `spec`=0). MySQL error: "Unknown column 'current_rank' in 'field list'" (Error #1054)<br />

**Comment by Shadez** [comment]
This should be fixed after [462] rev. Thank you!

**Comment by SignFinder** [comment]
спасибо вам за армори.
