### ISSUE TITLE
XML Error

### ISSUE THREAD

**Issue by Wimboss** [Shadez/wowarmory#120]
XML-Verarbeitungsfehler: "Junk" nach Dokument-Element
Adresse: http://arsenal.fantasy-wow.eu/character-sheet.xml?r=Highrate&cn=Sargonnas
Zeile Nr. 2, Spalte 1:

<b>Warning</b>:  sprintf() [<a href='function.sprintf'>function.sprintf</a>]: Too few arguments in <b>/usr/www/users/fantasx/arsenal/includes/classes/class.debug.php</b> on line <b>64</b><br />
^

**Comment by jonkopinx** [comment]
hmm, are the characters class that you want to view is Rogue?

same problem with me here, whenever i tried to view Rogue Class, this error show up.

**Comment by Wimboss** [comment]
no dk´s

**Comment by Shadez** [comment]
Sorry for long response. This issue should be fixed in [464] rev. Please, test it and report back.
Thank you!

**Comment by jonkopinx** [comment]
thanks !.
