### ISSUE TITLE
Can't find Characters...

### ISSUE THREAD

**Issue by jammedejaldo** [Shadez/wowarmory#122]
Hey,

Good work Shadez, the armory page works fine. But I have one problem.
I made a character, but when I logged in then he can't find my character.
When I click on "More Characters" then he found it, when I click on my character
he said "File Not Found". Can you help me please with this issue?

I use rev: 450 (newest database I think).

Debug said:

<strong>DEBUG</strong> [26-01-2011 16:38:26]: ArmoryDatabaseHandler::_query : unable to execute SQL query (SELECT `data` FROM `armory_character_stats` WHERE `guid` = 2 LIMIT 1). MySQL error: "Table 'characters.armory_character_stats' doesn't exist" (Error #1146)<br />
<strong>ERROR</strong> [26-01-2011 16:38:26]: Characters::BuildCharacter : player 2 (Testname) has no data in `armory_character_stats` table (SQL update to Characters DB was not applied? / Character was not saved in game? / Server core was not patched?)<br />
<strong>ERROR</strong> [26-01-2011 16:38:26]: Achievements::InitAchievements : wrong player guid (0), ignore.<br />
<strong>ERROR</strong> [26-01-2011 16:38:26]: Achievements::CalculateAchievementPoints : unable to find any completed achievements for player 2<br />
<strong>ERROR</strong> [26-01-2011 16:38:26]: Achievements::CalculateAchievementPoints : unable to find any completed achievements for player 2<br />
<strong>DEBUG</strong> [26-01-2011 16:38:26]: Utils::GetBookmarks : bookmarks for account 3 not found<br />

Thanks,

Jamie

**Comment by Shadez** [comment]
Closed as non-related to Armory bugs. Patch your core, log in game with selected character and log out. Table `armory_character_stats` will be filled with required infos. Then open armory again.

**Comment by jammedejaldo** [comment]
Thanks Shadez, but do you know where you have a tutorial how to patch that?

**Comment by Shadez** [comment]
In GIT Console, for example:
`patch -p1 < wowarmory_patch.patch`

**Comment by jammedejaldo** [comment]
Shadez, I installed the GIT console. When I type "cmd" and after that I type "GIT" then I see the commands, but when I type:
<code>patch -p1 < wowarmory_patch.patch</code> then it won't work.. I compiled a totally new trinity core but still not work. How can you help me? do you want add me to see it? jamiedejong91@live.nl. This problem must be solved..

**Comment by jammedejaldo** [comment]
It's already working, I know how to patch now with the GIT console.
It was: git apply wowarmory_patch.patch and then enter. That works.
But he gave warnings to the wowarmory_patch.patch and the wowarmory_arena_chart.patch didn't patch (patch failed). The warnings are:
[.h or .cpp] has type 100644, expected 100755. Do you have the new patch files for me please? that other issue from me you can close.

**Comment by Shadez** [comment]
Try with newest patch file that was added in [466] rev.

**Comment by jammedejaldo** [comment]
I downloaded the newest patch file [466] rev. I put that two files in my source folder of Trinity (C:\Trinity) and then I open "CMD" and go to the folder and type: git apply "wowarmory_patch.patch" but its still saying has type 100644, expected 100755. Shadez, see my topic (more information): http://www.trinitycore.org/f/index.php?/topic/872-armory-apply-patch-error

**Comment by Shadez** [comment]
Right click on your Sources folder and select "Git bash here". In console type 
`patch -p1 < wowarmory_patch.patch` and press enter. This works for me.

**Comment by jammedejaldo** [comment]
Thanks Shadez, I think it's working now, Im compiling the Trinity Core now.
A little question, do I still need to execute that character_patch.sql file into the character database? Thanks for helping me! I will test it!

**Comment by Shadez** [comment]
Of course you need to execute SQL dump (if you haven't already updated your DB with these SQL queries).

**Comment by jammedejaldo** [comment]
Oke Shadez, thanks for your help. I will let you know here if its working! :) Thanks for learning me about patching etc...! =D Patching works alone with Git bash here...

**Comment by jammedejaldo** [comment]
It's not working :( still I got "File Not Found". The armory_character_stats table is still empty. How to fix this issue?

**Comment by jammedejaldo** [comment]
This is my debug now:

<code>
<strong>ERROR</strong> [29-01-2011 19:41:12]: Characters::BuildCharacter : unknown server type! Unable to initialize characters class (character name: Hawk, realmId: 1)<br />
<strong>ERROR</strong> [29-01-2011 19:41:12]: Achievements::InitAchievements : wrong player guid (0), ignore.<br />
<strong>ERROR</strong> [29-01-2011 19:41:12]: Achievements::CalculateAchievementPoints : unable to find any completed achievements for player 1<br />
<strong>ERROR</strong> [29-01-2011 19:41:12]: Achievements::CalculateAchievementPoints : unable to find any completed achievements for player 1<br />
<strong>DEBUG</strong> [29-01-2011 19:41:12]: Utils::GetBookmarks : bookmarks for account 1 not found<br />
</code>

**Comment by Shadez** [comment]
> unknown server type!

Set $ArmoryConfig['multiRealm'][REALM_ID]['type'] value to SERVER_MANGOS or SERVER_TRINITY _without_ apostrophes.

> The armory_character_stats table is still empty. How to fix this issue?

Log in game, .save character or log off. Then refresh character sheet.

**Comment by jammedejaldo** [comment]
Sorry for flooding, because I fixed the first ERROR of my debug.
The armory_character_stats table is now filled! but still "File Not Found" see my new debug:
<code>
<strong>DEBUG</strong> [29-01-2011 19:49:05]: Characters::IsCharacterFitsRequirements : unable to load character Hawk (GUID: 1): level restriction.<br />
<strong>ERROR</strong> [29-01-2011 19:49:05]: Achievements::InitAchievements : wrong player guid (0), ignore.<br />
<strong>ERROR</strong> [29-01-2011 19:49:05]: Achievements::CalculateAchievementPoints : unable to find any completed achievements for player 1<br />
<strong>ERROR</strong> [29-01-2011 19:49:05]: Achievements::CalculateAchievementPoints : unable to find any completed achievements for player 1<br />
<strong>DEBUG</strong> [29-01-2011 19:49:05]: Utils::GetBookmarks : bookmarks for account 1 not found<br />
</code>

**Comment by Shadez** [comment]
Please, read debug/error messages more carefuly.
It says:

> Characters::IsCharacterFitsRequirements : unable to load character Hawk (GUID: 1): level restriction.

This means, that you need to level your character to 10+ lvl or change ArmoryConfig['settings']['minlevel'] value to more lower than 10 (1 for example to display all characters).

**Comment by jammedejaldo** [comment]
Thanks Shadez! it's working now! YEA! but it doesn't show the gm's I have give my self level 3 and it doesn't show my character how to fix that?

**Comment by Shadez** [comment]
Just read all useful info that provides with Armory package (INSTALL file, 3DViewer_info.txt, comments in configuration.php).
