### ISSUE TITLE
File Not Found!

### ISSUE THREAD

**Issue by jammedejaldo** [Shadez/wowarmory#123]
Hey people,

Everything works fine of the armory but I have one problem. I can't see the characters, when I click on the character name it will said: "File Not Found".

This is my database,

auth = realm database
characters = character database
trinity = world database

I already execute the "characters_patch.sql" file into the characters database.
I use the newest rev. 450 from Shadez. So I don't need any updates.
I didn't patch the two files yet, because I don't know how to patch...

I have read some other comments about the same problem and there is a comment, if the "armory_character_stats" is empty then you must patch that two files in \tools\trinity_core. I hope someone can explain me how to patch that two files.

This is my configuration.php,

<code>
$ArmoryConfig['mysql']['host_armory']     = 'localhost';
$ArmoryConfig['mysql']['user_armory']     = 'root';
$ArmoryConfig['mysql']['pass_armory']     = 'mypassword';
$ArmoryConfig['mysql']['name_armory']     = 'armory';
$ArmoryConfig['mysql']['charset_armory']  = 'UTF8';
$ArmoryConfig['mysql']['host_realmd']     = 'localhost';
$ArmoryConfig['mysql']['user_realmd']     = 'root';
$ArmoryConfig['mysql']['pass_realmd']     = 'mypassword';
$ArmoryConfig['mysql']['name_realmd']     = 'auth';
$ArmoryConfig['mysql']['charset_realmd']  = 'UTF8';
</code>

<code>
$ArmoryConfig['multiRealm'][1]['id']                 = 1;
$ArmoryConfig['multiRealm'][1]['name']               = 'Trinity';
$ArmoryConfig['multiRealm'][1]['type']               = SERVER_TRINITY;
$ArmoryConfig['multiRealm'][1]['host_characters']    = 'localhost';
$ArmoryConfig['multiRealm'][1]['user_characters']    = 'root';
$ArmoryConfig['multiRealm'][1]['pass_characters']    = 'mypassword';
$ArmoryConfig['multiRealm'][1]['name_characters']    = 'characters';
$ArmoryConfig['multiRealm'][1]['charset_characters'] = 'UTF8';
$ArmoryConfig['multiRealm'][1]['host_world']         = 'localhost';
$ArmoryConfig['multiRealm'][1]['user_world']         = 'root';
$ArmoryConfig['multiRealm'][1]['pass_world']         = 'mypassword';
$ArmoryConfig['multiRealm'][1]['name_world']         = 'characters';
$ArmoryConfig['multiRealm'][1]['charset_world']      = 'UTF8';
</code>

I have a little question about the configuration.php too, why doesn't have the ID and TYPE these signs ( ' ' ) ?

And at least you need my debug, these bugs will come when I click on my character name on the armory site from Shadez.

<code>
<strong>ERROR</strong> [27-01-2011 16:06:39]: Characters::BuildCharacter : player 2 (Test) has no data in `armory_character_stats` table (SQL update to Characters DB was not applied? / Character was not saved in game? / Server core was not patched?)<br />
<strong>ERROR</strong> [27-01-2011 16:06:39]: Achievements::InitAchievements : wrong player guid (0), ignore.<br />
<strong>ERROR</strong> [27-01-2011 16:06:40]: Achievements::CalculateAchievementPoints : unable to find any completed achievements for player 2<br />
<strong>ERROR</strong> [27-01-2011 16:06:40]: Achievements::CalculateAchievementPoints : unable to find any completed achievements for player 2<br />
<strong>DEBUG</strong> [27-01-2011 16:06:40]: Utils::GetBookmarks : bookmarks for account 5 not found<br />
</code>

**Comment by jammedejaldo** [comment]
I think that I have found the problem, the table "armory_character_stats" is empty, when he's empty I must patch the core, but can you explain me how I can patch that two files?  I did right click on the patch file and then I said Tortoise -> Apply Patch and after that I can choose a folder for the output I think, but when I did that I dont see anything in that folder... is there a other way to fix it?

**Comment by Shadez** [comment]
> I have a little question about the configuration.php too, why doesn't have the ID and TYPE these signs ( ' ' ) ?

Because these values are integers, they do not need apostrophes.
I'm closing this issue as non-related to Armory bugs. Read special threads on forums (MaNGOS or TC) for patching info.

**Comment by jammedejaldo** [comment]
Hey Shadez,

I know how to patch now, I think the patch files are not good. Because when I patch it in cmd it said:

<code>
Warning: src/server/game/Achievements/AchievementMgr.cpp has type 100644, expected 100755
</code>

This is also for the other patch, he didn't patch it. Do you have the new files?

Thanks!
