### ISSUE TITLE
Search.xml - Error

### ISSUE THREAD

**Issue by YannickFricke** [Shadez/wowarmory#125]
Hello,
I have a Problem :D:D

SO I updated the database on the newest update, he said, wrong version: so I went into the db and changed the rev-number.
the next problem is: that the file search.xml isn't avaiable for all.
so you made a mistake in declaring the search.xml. It must be search.php

Greetings from Germany,
FrickX

**Comment by Shadez** [comment]
Configure mod_rewrite module for your Apache server.
