### ISSUE TITLE
[TC] ¡Primeros logros!

### ISSUE THREAD

**Issue by Gooyeth** [Shadez/wowarmory#127]
Los primeros logros de raids se muestran individualmente, es decir si hay una raid de 25 salen 25 logros individuales. Una imagen del error:
http://img844.imageshack.us/img844/1153/primeroslogros.png

¿Como debe ser?

Tendría que salir un logro con el nombre de todos los personajes participantes en la raid. Una imagen:
http://img573.imageshack.us/img573/3504/primeroslogros2.png

Gracias ^^

**Comment by Shadez** [comment]
Yes, I know about this issue. Will look deeper into this problem, thank you.

**Comment by Shadez** [comment]
Implemented in <a href="https://github.com/Shadez/wowarmory/commit/1d7ec2dca8119f0d1b7806314e32beca56542d6c">[468]</a>. Enjoy!

**Comment by Gooyeth** [comment]
Muchas gracias ^^
