### ISSUE TITLE
Trinitycore 3.3.3a + .patch + sqls (rev 211)

### ISSUE THREAD

**Issue by Gomez22** [Shadez/wowarmory#13]
1. Achievement Page + Achievement points not displayed
   XML Parsing Error: junk after document element
   Location: http://******_/character-achievements.xml?r=Divine&cn=Joel&gn=Friendly
   Line Number 2, Column 1:<b>Warning</b>:  Invalid argument supplied for foreach() in <b>/home/a77366812/domains/**_****/public_html/armory/includes/classes/class.achievements.php</b> on line <b>171</b><br />
2. 2v2 Arena Ladder Results shows nothing
3. Cache works, becouse loading time is not quite "fast" ?

**Comment by Gomez22** [comment]
1. XML Parsing Error: junk after document element
   Location: http://********_/character-select.xml
   Line Number 2, Column 1:
   <b>Notice</b>:  Undefined index:  id in <b>/home/a77366812/domains/**_****/public_html/armory/includes/classes/class.utils.php</b> on line <b>170</b><br />
   ^

**Comment by Gomez22** [comment]
1. You should try for "future update" to eliminate blizzard links, like store, and forums

**Comment by Shadez** [comment]
> Cache works, becouse loading time is not quite "fast" ?

Cache is added in order to avoid causing a database overload

Other problems should be fixed in 212 revision, thank you.

**Comment by Gomez22** [comment]
Testing right now :) I, thank you

**Comment by Shadez** [comment]
> Notice: Undefined index: id in /home/a77366812/domains//public_html/armory/includes/classes/class.utils.php on line 170

Update configuration.php
