### ISSUE TITLE
Error Again

### ISSUE THREAD

**Issue by Vezax** [Shadez/wowarmory#132]
i after click to item , weapon , glyph , gem and.... error

XML Parsing Error: junk after document element
Location: http://127.0.0.1/web/armory/search.xml?source=all&type=projectiles&subTp=arrow&searchType=items
Line Number 2, Column 1:<b>Warning</b>:  Invalid argument supplied for foreach() in <b>C:\xampp\htdocs\web\armory\includes\classes\class.search.php</b> on line <b>409</b><br />
^

**Comment by Shadez** [comment]
Fixed in <a href="https://github.com/Shadez/wowarmory/commit/a497a7196e996f61e31643f65a25eb2fe80fd0c9">[472]</a>, thank you!
