### ISSUE TITLE
error in ver [ 474 ] 

### ISSUE THREAD

**Issue by Vezax** [Shadez/wowarmory#134]
XML Parsing Error: junk after document element
Location: http://127.0.0.1/web/armory/character-sheet.xml?r=wow&cn=Dsa
Line Number 2, Column 1:<b>Notice</b>:  Undefined index: Rank_2 in <b>C:\xampp\htdocs\web\armory\includes\classes\class.characters.php</b> on line <b>3069</b><br />
^

**Comment by Shadez** [comment]
Fixed in <a href="https://github.com/Shadez/wowarmory/commit/5992681ddcb1d7302147b611e8b695bb4be2e358">[475]</a>, thank you!
