### ISSUE TITLE
Error in [475]

### ISSUE THREAD

**Issue by Vezax** [Shadez/wowarmory#135]
XML Parsing Error: junk after document element
Location: http://127.0.0.1/web/armory/character-sheet.xml?r=wow&cn=Dsa
Line Number 2, Column 1:<b>Notice</b>:  Undefined offset: 1 in <b>C:\xampp\htdocs\web\armory\includes\classes\class.characters.php</b> on line <b>3070</b><br />
^

Trinitycore version

**Comment by Shadez** [comment]
The most problem method :( I hope I wasn't drunk when I was wrote this :)
Thank you, should be fixed in <a href="https://github.com/Shadez/wowarmory/commit/11997db83d0f4818764f36f2903a67cbe44b5233">[476]</a>!

**Comment by Vezax** [comment]
Hi shadez not fix in 476

**Comment by Shadez** [comment]
Hmm.. Still the same line number?

**Comment by Vezax** [comment]
yes
XML Parsing Error: junk after document element
Location: http://127.0.0.1/web/armory/character-sheet.xml?r=wow&cn=Dsa
Line Number 2, Column 1:<b>Notice</b>:  Undefined offset: 1 in <b>C:\xampp\htdocs\web\armory\includes\classes\class.characters.php</b> on line <b>3070</b><br />
^
My version [476]

**Comment by Shadez** [comment]
Fixed in <a href="https://github.com/Shadez/wowarmory/commit/9e8eef5d017bf59af320a85ec643294f199019af">[477]</a>
