### ISSUE TITLE
Cant view chars rev 476

### ISSUE THREAD

**Issue by maximgeerinck** [Shadez/wowarmory#136]
<br /> 
<b>Notice</b>:  Undefined index:  skipBanned in <b>/home/ace/public_html/armory/includes/classes/class.characters.php</b> on line <b>321</b><br /> 
<br /> 
<b>Notice</b>:  Undefined offset:  1 in <b>/home/ace/public_html/armory/includes/classes/class.characters.php</b> on line <b>3070</b><br /> 
<br /> 
<b>Notice</b>:  Undefined offset:  1 in <b>/home/ace/public_html/armory/includes/classes/class.characters.php</b> on line <b>3074</b><br /> 

u can view this when u view the source

please help me whit this

**Comment by Shadez** [comment]
> Notice: Undefined index: skipBanned in /home/ace/public_html/armory/includes/classes/class.characters.php on line 321

Seem that your configuration.php is outdated. Please, update it from configuration.php.default

About other errors - I am compiling Trinity Core server right now to see what exactly fails. Will be fixed as far as possible.

**Comment by maximgeerinck** [comment]
well i have fixed that error and now it sais

File Not Found
This character profile could not be displayed, possibly for one of the following reasons:
The character has been inactive for an extended period of time.
The character name was spelled incorrectly.
The profile is temporarily unavailable while the character is in the midst of a process such as a realm transfer or faction change.
Characters that have been deleted are no longer available on the Armory.

**Comment by Shadez** [comment]
Some info from debug log?

**Comment by maximgeerinck** [comment]
yes 

EBUG [13-02-2011 05:45:25]: Characters::BuildCharacter : all correct, player Armorywoot (GUID: 141428, raceID: 10, classID: 6, level: 80) loaded, class has been initialized.
ERROR [13-02-2011 05:45:25]: Characters::CalculateCharacterTalents : unable to get data from DB for player 141428 (Armorywoot)
ERROR [13-02-2011 05:45:25]: Characters::GetCharacterItemInfo : slot 3 is empty (nothing equipped?)
ERROR [13-02-2011 05:45:26]: Characters::GetCharacterItemInfo : slot 13 is empty (nothing equipped?)
ERROR [13-02-2011 05:45:26]: Characters::GetCharacterItemInfo : slot 15 is empty (nothing equipped?)
ERROR [13-02-2011 05:45:26]: Characters::GetCharacterItemInfo : slot 16 is empty (nothing equipped?)
ERROR [13-02-2011 05:45:26]: Characters::GetCharacterItemInfo : slot 17 is empty (nothing equipped?)
ERROR [13-02-2011 05:45:26]: Characters::GetCharacterItemInfo : slot 18 is empty (nothing equipped?)
DEBUG [13-02-2011 05:45:31]: Characters::BuildCharacter : all correct, player Armorywoot (GUID: 141428, raceID: 10, classID: 6, level: 80) loaded, class has been initialized.
ERROR [13-02-2011 05:45:31]: Characters::CalculateCharacterTalents : unable to get data from DB for player 141428 (Armorywoot)
ERROR [13-02-2011 05:45:32]: Characters::GetCharacterItemInfo : slot 3 is empty (nothing equipped?)
ERROR [13-02-2011 05:45:32]: Characters::GetCharacterItemInfo : slot 13 is empty (nothing equipped?)
ERROR [13-02-2011 05:45:32]: Characters::GetCharacterItemInfo : slot 15 is empty (nothing equipped?)
ERROR [13-02-2011 05:45:32]: Characters::GetCharacterItemInfo : slot 16 is empty (nothing equipped?)
ERROR [13-02-2011 05:45:32]: Characters::GetCharacterItemInfo : slot 17 is empty (nothing equipped?)
ERROR [13-02-2011 05:45:32]: Characters::GetCharacterItemInfo : slot 18 is empty (nothing equipped?)
DEBUG [13-02-2011 06:00:45]: Characters::IsCharacterFitsRequirements : unable to display character Armorywoot (GUID: 141428): GM level restriction!
ERROR [13-02-2011 06:00:45]: Achievements::InitAchievements : wrong player guid (0), ignore.
DEBUG [13-02-2011 06:01:02]: Characters::IsCharacterFitsRequirements : unable to display character Armorywoot (GUID: 141428): GM level restriction!
ERROR [13-02-2011 06:01:02]: Achievements::InitAchievements : wrong player guid (0), ignore.

**Comment by Shadez** [comment]
> DEBUG [13-02-2011 06:01:02]: Characters::IsCharacterFitsRequirements : unable to display character Armorywoot (GUID: 141428): GM level restriction!
