### ISSUE TITLE
Cant view chars rev 476

### ISSUE THREAD

**Issue by maximgeerinck** [Shadez/wowarmory#137]
File Not Found
This character profile could not be displayed, possibly for one of the following reasons:
The character has been inactive for an extended period of time.
The character name was spelled incorrectly.
The profile is temporarily unavailable while the character is in the midst of a process such as a realm transfer or faction change.
Characters that have been deleted are no longer available on the Armory.

debug log
http://paste2.org/p/1244724

please help me whit this 

thx

**Comment by Shadez** [comment]
Properly configure your configuration.php - you have no realm info.

**Comment by maximgeerinck** [comment]
configuration is working now but it just doesnt show characters and sais file not found

**Comment by Shadez** [comment]
> but it just doesnt show characters and sais file not found

From your debug log:

> DEBUG [13-02-2011 06:01:02]: Characters::IsCharacterFitsRequirements : unable to display character Armorywoot (GUID: 141428): GM level restriction!

Chage value of ArmoryConfig[settings][minGmLevelToShow] according with comments.

**Comment by maximgeerinck** [comment]
thank you for that 

now i get this error :s

<br /> 
<b>Notice</b>:  Undefined offset:  1 in <b>/home/ace/public_html/armory/includes/classes/class.characters.php</b> on line <b>3070</b><br /> 
<br /> 
<b>Notice</b>:  Undefined offset:  1 in <b>/home/ace/public_html/armory/includes/classes/class.characters.php</b> on line <b>3074</b><br />

**Comment by Shadez** [comment]
Fixed in <a href="https://github.com/Shadez/wowarmory/commit/9e8eef5d017bf59af320a85ec643294f199019af">[477]</a>.

**Comment by maximgeerinck** [comment]
thanks this fixed it :)
