### ISSUE TITLE
Cant load tooltips -> google chrome

### ISSUE THREAD

**Issue by maximgeerinck** [Shadez/wowarmory#138]
hi i can't load tooltips when i mouseover an item

lots of errors like

ERROR [13-02-2011 13:26:23]: Item::LoadFromDB : item (GUID: 839924) was not found in `item_instance` table (server type: SERVER_TRINITY - 2)!
ERROR [13-02-2011 13:26:23]: Item::LoadFromDB : item (GUID: 839977) was not found in `item_instance` table (server type: SERVER_TRINITY - 2)!
ERROR [13-02-2011 13:26:23]: Item::LoadFromDB : item (GUID: 839990) was not found in `item_instance` table (server type: SERVER_TRINITY - 2)!
ERROR [13-02-2011 13:26:23]: Item::LoadFromDB : item (GUID: 840060) was not found in `item_instance` table (server type: SERVER_TRINITY - 2)!
ERROR [13-02-2011 13:26:23]: Item::LoadFromDB : item (GUID: 840113) was not found in `item_instance` table (server type: SERVER_TRINITY - 2)!
ERROR [13-02-2011 13:26:23]: Item::LoadFromDB : item (GUID: 840620) was not found in `item_instance` table (server type: SERVER_TRINITY - 2)!
ERROR [13-02-2011 13:26:23]: Item::LoadFromDB : item (GUID: 916950) was not found in `item_instance` table (server type: SERVER_TRINITY - 2)!

**Comment by Shadez** [comment]
Are these entries really stored in DB?

> SELECT \* FROM `item_instance` WHERE `guid` = itemguid AND `owner_guid` = playerguid

I guess that it's not Armory bug

**Comment by maximgeerinck** [comment]
i dont get it its a weird error and cant seem to fix it in firefox the tooltip works but in chrome it just sais LOADING... and then an empty tooltip

**Comment by Jildor** [comment]
Confirm, and not show talents character, freeze in chrome

**Comment by maximgeerinck** [comment]
still not working :S and its just in chrome and not in firefox or ie

**Comment by maximgeerinck** [comment]
r
