### ISSUE TITLE
Case Sensitive

### ISSUE THREAD

**Issue by Exordian** [Shadez/wowarmory#139]
There is an issue if 2 guilds had the same name, but different spellings, only one guild is shown.

For Example:
you have "Test" and "TEST", and you're searching for test, both guilds are shown but if you click on TEST you'll be redirected to Test.

**Comment by Shadez** [comment]
Implemented in <a href="https://github.com/Shadez/wowarmory/commit/8c31ecad0fe34576113fbc1661a1cd5b755b737d">[483]</a>, thank you!
