### ISSUE TITLE
2v2 Arena Ladder Results - Trinitycore 214

### ISSUE THREAD

**Issue by Gomez22** [Shadez/wowarmory#14]
This time show teams but the rank is wrong (lots of zero rank and same rank) and is starts with last rank (like 300 not from 1)

My suggestion is to avoid take rank from characters table and use "rank" as row number to avoid many teams with same rank ( I don`t know if is normal to have same rank but I think not )

**Comment by Gomez22** [comment]
Screens:
http://www.freehostpicture.com/images/86394529582498743818.jpg
http://www.freehostpicture.com/images/82575243483032471996.jpg

Another error:

Login page, You can login ONLY on gm accounts, if you try with a normal account your password won`t match

**Comment by Gomez22** [comment]
Another error:

Profile Page:
Notice: Undefined index: id in /home/a77366812/domains/*****/public_html/armory/includes/classes/class.characters.php on line 204

**Comment by Shadez** [comment]
> Notice: Undefined index: id in /home/a77366812/domains/*****/public_html/armory/includes/classes/class.characters.php on line 204

Update your configuration.php (there're some new values in configuration.php.default)

> Login page, You can login ONLY on gm accounts, if you try with a normal account your password won`t match

Can't confirm that - account with gmlevel 0 successfully logs in.

About arena ladder: more news will be availabe when somebody'll provide me sql dump with characters DB (requested in Wowarmory thread on getmangos.com)

**Comment by gyullo** [comment]
a Little fix is add
WHERE arena_team.ranking > 0
to the SQL query, so not ranking team is not shown

here is an example, i use this armory for my server and make a little change like emblem colors:
http://wow.localstrike.com.ar/Armory/arena-ladder.xml?ts=5&b=Localstrike

is this is some kind of spawn is not what im trying to do, just to show you the result with add ranking>0 to the query

"The lot os same rank" issue is a core problem, that im trying to solve

**Comment by Shadez** [comment]
Should be fixed in <a href="http://github.com/Shadez/wowarmory/commit/f886f0a2251baba66b519b300cad71a14a7af59c">238 rev.</a>
