### ISSUE TITLE
Cant View Tooltips from armor (CHAR) in chrome

### ISSUE THREAD

**Issue by maximgeerinck** [Shadez/wowarmory#140]
hi i cant view any tooltip when i mouseover the gear from a character in google chrome this works fine though in firefox :S

http://oldschool-wow.com/armory/character-sheet.xml?r=Campfire&cn=Angryballz

u can check it
there are no errors related to this issue 

Please help me whit this i need it badly
regards C4D3R

**Comment by Jildor** [comment]
Confirm, any solution?

**Comment by TipoDeIncognito** [comment]
I have fix this, i have get Original JS from wowarmory (http://cn.wowarmory.com/_js/armory.js) and fix some func, i are testing in all browsers just now

**Comment by maximgeerinck** [comment]
still havent fixed this :s can somebody help please
