### ISSUE TITLE
Imagenes "Posición arena"

### ISSUE THREAD

**Issue by Gooyeth** [Shadez/wowarmory#141]
Bueno, traigo un pequeño reporte, y es que en la imagen donde muestra la posición del team de arena no la muestra completamente. Aquí una imagen del problema:

<img src="http://img193.imageshack.us/img193/5072/armoryc.png" />

Debería mostrarlo así:

<b>Alianza:</b>
<img src="http://img64.imageshack.us/img64/8169/alianzaa.png" />

<b>Horda:</b>
<img src="http://img833.imageshack.us/img833/1396/horda.png"/>

Es un reporte pequeño pero hasta el momento es uno de los problemas que he visto, cualquier otra cosa la reporto. Gracias ^^

**Comment by Shadez** [comment]
Thank you, I'll check this a little bit later

**Comment by Shadez** [comment]
Information about team faction added in <a href="https://github.com/Shadez/wowarmory/commit/5d07d76a8ad3d091888963ff5ed98e40026bda2a">[485]</a>.
