### ISSUE TITLE
Nombres de personajes similares 1 resultado.

### ISSUE THREAD

**Issue by Gooyeth** [Shadez/wowarmory#142]
Los nombres de los personajes por ejemplo "Armory", "Armöry", "Armóry" (entre más caracteres) se muestra siempre un solo resultado y un solo personaje, todos los nombres similares se muestran el mismo personaje. Espero ser claro XD

Gracias nuevamente ;)

**Comment by Shadez** [comment]
Sorry, but I don't understand: you mean that in search results there is only 1 character or all characters are present, but special symbols are not display?

**Comment by Gooyeth** [comment]
Por ejemplo:

Hay dos personajes uno se llama "Armory" y otro "Armöry" si los buscas en la armería siempre sale 1 resultado de un personaje (en este caso saldría Armory), sin embargo si buscas por ejemplo:
<a href="http://127.0.0.1/character-sheet.xml?r=Reino&cn=Armory">http://127.0.0.1/character-sheet.xml?r=Reino&cn=Armory</a></br>
<a href="http://127.0.0.1/character-sheet.xml?r=Reino&cn=Armöry">http://127.0.0.1/character-sheet.xml?r=Reino&cn=Armöry</a> (me cambia el link ¬¬, igual es lo mismo XD)

Siempre saldrá el mismo personaje (como resultado 1 personaje), es decir la armería no diferencia o no reconoce los caracteres "raros" en los personajes por lo que hará que se vea sólo un personaje y no dos diferentes como debería ser. Gracias ;).

**Comment by Jildor** [comment]
Es decir, ¿que no reconoce caracteres especiales en los nombres de los jugadores?

English:
That is, does not recognize special characters in the names of the players?

**Comment by Gooyeth** [comment]
Eso mismo XD

Es algo dificil de explicar :S, y si un personaje tiene caracteres especiales ese personaje no sale en la armería, saldría el perfil del que no tiene caracteres especiales.

**Comment by Shadez** [comment]
So, if I'm understood you right:
you have two characters - "Armory" and "Armöry". If you want to browse "Armöry's" page, script loads "Armory's" page instead of the correct one. Right? If yes, update to <a href="https://github.com/Shadez/wowarmory/commit/f7a4817bd3112fff3d019bc8d7e6a6294c43398e">[484]</a> revision. If no, try to explain it more better - I'm using Google Translate to understand you :-)

**Comment by Jildor** [comment]
ALTER DATABASE  `WORLD_DB` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci

ALTER DATABASE  `CHAR_DB` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci

ALTER DATABASE  `REALM_DB` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci

and solved :D
