### ISSUE TITLE
problem armory and db

### ISSUE THREAD

**Issue by C0urage** [Shadez/wowarmory#143]
Hi, I have problems with armory.
 I have tested locally and it works. I put on my ftp server and I modified the file "config.php" with my access.
 I applied correctly in the sql db files and correctly applied the patch core.
This is the error:
Fatal error: wrong DB name Armory
DB_VERSION error:
Current version is not defined but expected 'armory_r471'.
Apply all updates from neccessary 'sql / updates' folder and refresh this page

I checked the access to the database and a custom script I tested the accessibility. everything was ok.

I noticed, however, that in the debug file does not write anything on ftp, and in local access server gives me this error:
ERROR: [02/18/2011 16:27:25]: ArmoryDatabaseHandler: ArmoryDatabaseHandler: unable to connect to MySQL Server (host: "**_.**_.**.**", dbName: "web" ). Error: none. Check your configs.
ERROR [18/02/2011 16:27:46]: ArmoryDatabaseHandler: ArmoryDatabaseHandler: unable to connect to MySQL Server (host: "**_.**_.**.**", dbName: "auth") . Error: none. Check your configs.

I hope someone can help me.
Thanks in advance and I apologize for the bad English.

**Comment by camesenin** [comment]
I have same problem

Any Solution?

**Comment by Jildor** [comment]
UPDATE `armory_db_version` SET `version` = 'armory_r471' ;

**Comment by C0urage** [comment]
@jildor not work. the db version is correct.
