### ISSUE TITLE
Wrong Date on Arena Match History Graph

### ISSUE THREAD

**Issue by peycho** [Shadez/wowarmory#144]
I thins there's a problem with showing date of Arena Match History Graph.

Here is screen shot: http://files.alein.org/images/bugs/wrong_date.jpg

Armory db version: armory_r471 (5d07d76a8ad3d091888963ff5ed98e40026bda2a)
Server Trinity Core + patches (wowarmory_arena_chart.patch, wowarmory_patch.patch) from /tools/trinity_core

In database date start/end colums show something like that:

http://files.alein.org/images/bugs/armory_game_chart.txt

**Comment by Shadez** [comment]
Oh.. Very old bug, which I forgot. I'll fix this ASAP. Thank you!
