### ISSUE TITLE
Achievement first

### ISSUE THREAD

**Issue by maximgeerinck** [Shadez/wowarmory#145]
Hi

at the 
achievement-firsts.xml
when u have multiple realms u see viewing
then ur realm name but when i want to select my second realm then there doesnt show anything (only a search field which doesnt work when i try to search for that second realm name)
debug shows nothing

**Comment by Shadez** [comment]
I can't reproduce this bug:
http://i51.tinypic.com/281v2mx.jpg
http://i53.tinypic.com/2l89gd2.jpg
Maybe some more info, please?

**Comment by maximgeerinck** [comment]
http://tinypic.com/r/f527iu/7
here is a screenshot
there should be 2 realms normally but its only showing one :s

**Comment by Shadez** [comment]
Oh.. you're talking about that.
Look here: 

http://cn.wowarmory.com/achievement-firsts.xml?r=Sargeras

http://cn.wowarmory.com/achievement-firsts.xml?r=Deepfury

Not a bug.
