### ISSUE TITLE
.xml > .php

### ISSUE THREAD

**Issue by Darktron-zz** [Shadez/wowarmory#146]
Hola tengo un problema en mi armeria, la configuracion de la DB va bien pero cuando voy a algun link me dirige a http://midominio.com/search.xml y me dice que no encuentra el archivo pero si cambio xml por php si que me funciona.
Creo que el problema esta en el .htaccess ya que lo he tenido que borrar porque si lo ponia me daba un InternalError 500 y quitandolo no me da error, pero quitandolo no me funciona nada.

Que hago?

Saludos, Darktron.

**Comment by Shadez** [comment]
Just configure your Apache server to work with .htaccess files.
Closed as non related issue.
