### ISSUE TITLE
Configurar Apache > .htaccess

### ISSUE THREAD

**Issue by Darktron-zz** [Shadez/wowarmory#147]
Hola Shadez, me dijiste que configure el apache para que pueda trabajar con los .htacces pero no se como configurarlo, por favor me puedes ayudar?

Saludos, Darktron.

**Comment by Shadez** [comment]
There are a lot of guides about it in Google. Don't be shy to use it :)
Please, discuss only Armory bugs here (code, template, missed files, etc. but not your server configuration issues).
Thank you
