### ISSUE TITLE
New problem database

### ISSUE THREAD

**Issue by C0urage** [Shadez/wowarmory#148]
Fatal error: wrong Armory DB name
DB_VERSION error:
Current version is not defined but expected 'armory_r471'.
Apply all neccessary updates from 'sql/updates' folder and refresh this page.

this is the error:

DEBUG [09-03-2011 15:23:55]: ArmoryDatabaseHandler::_query : unable to execute SQL query (SELECT `version` FROM `armory_db_version`). MySQL error: none

I applied all the patches to the core and all updates to the database.
 Armory in the database version is: 'armory_r471'.

 any solution?

**Comment by Jildor** [comment]
Are you configured configuration.php ?

**Comment by C0urage** [comment]
yes. Initially I had another problem: will not connect to the database.
 now I have solved by creating a new database with the db characters and db auth.
 appears to connect, but does not run the query.

 The installation requirements are all ok.

**Comment by NeTw0rK** [comment]
Ingles: 
I have the same problem, but it is curious that the system If it detects that there are 5 characters in that account.

Español:
Tengo el mismo problema, pero es curioso que el sistema Sí detecte que existen 5 personajes en esa cuenta.

<strong>DEBUG</strong> [13-03-2011 23:16:22]: Utils::GetBookmarks : bookmarks for account 5 not found<br />
<strong>DEBUG</strong> [13-03-2011 23:30:39]: ArmoryDatabaseHandler::_query : unable to execute SQL query (SELECT SUM(`points`) FROM `armory_achievement` WHERE `id` IN ()). MySQL error: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1" (Error #1064)<br />

**Comment by C0urage** [comment]
Your should be a syntax error.
 my no. can someone help me?
 Shadez?

**Comment by Shadez** [comment]
Please, re-check your Armory MySQL DB connection info. Wrong connection info causes this error.
Closed.

**Comment by Mrbytes** [comment]
(SELECT SUM(`points`) FROM `armory_achievement` WHERE `id` IN ()). MySQL error: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1" (Error #1064)

This is my error, it´s the same of NeTw0rk say before, any solutions, please.

Best regards
