### ISSUE TITLE
Internet Explorer 8 error - for future development

### ISSUE THREAD

**Issue by Gomez22** [Shadez/wowarmory#15]
The XML page cannot be displayed 
Cannot view XML input using XSL style sheet. Please correct the error and then click the Refresh button, or try again later. 

---

Only one top level element is allowed in an XML document.

**Comment by Darkrevange** [comment]
I have same problem :| is there any solution for this error ?

**Comment by Gomez22** [comment]
Solution will be to use another browser like Firefox for example, at least until get fixed
