### ISSUE TITLE
Trinity Patch

### ISSUE THREAD

**Issue by alcsilian** [Shadez/wowarmory#151]
Hey. What we do about trinity patch since it doesn't apply? Could you help us out please?!

**Comment by mihawk90** [comment]
The Patch itself woks, just apply manually...

Patch-File seems to be broken but you can apply all changes manually

**Comment by robertyanta** [comment]
need some help, how can i apply the patch manually???, i dont understand, when i type git apply --check wowarmory_patch.patch on root dir of the trinitycore code i just get these errors/warnings:

warning: src/server/game/Achievements/AchievementMgr.cpp has type 100644, expected 100755
error: patch failed: src/server/game/Achievements/AchievementMgr.cpp:1951
error: src/server/game/Achievements/AchievementMgr.cpp: patch does not apply
warning: src/server/game/Entities/Item/Item.cpp has type 100644, expected 100755
error: patch failed: src/server/game/Entities/Item/Item.cpp:278
error: src/server/game/Entities/Item/Item.cpp: patch does not apply
warning: src/server/game/Entities/Player/Player.cpp has type 100644, expected 100755
error: patch failed: src/server/game/Entities/Player/Player.cpp:4908
error: src/server/game/Entities/Player/Player.cpp: patch does not apply
warning: src/server/game/Entities/Player/Player.h has type 100644, expected 100755
error: patch failed: src/server/game/Entities/Player/Player.h:1028
error: src/server/game/Entities/Player/Player.h: patch does not apply
warning: src/server/game/Entities/Unit/Unit.cpp has type 100644, expected 100755
error: patch failed: src/server/game/Entities/Unit/Unit.cpp:15177
error: src/server/game/Entities/Unit/Unit.cpp: patch does not apply

**Comment by mihawk90** [comment]
I mean not apply via patchfile and git, but apply change by change by hand in VisualStudio or whatever editor you are using.
So no automatic applying via git, but manually by hand.

**Comment by robertyanta** [comment]
ok mihawk90, thanks for your fast anwser, did it and works great, thanks again....
think the topic can be closed now
