### ISSUE TITLE
Problem in config , help and thnks u work so nice!

### ISSUE THREAD

**Issue by MagicWizard** [Shadez/wowarmory#152]
All right but I can not even see the characters changing the level of gmshow 1-2 - or 3, to activate the 3D viewer gets into the core as the patch can provide me with the linux command to finish setting up your great work thanks and regards

**Comment by Wortex** [comment]
I suggest you use some proper grammar, cuz from what you've just typed I cant figure out your problem...

Proper description of the error will always help the people whom wish to help you understand the problem better and, maybe, help you faster.
