### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by Vezax** [Shadez/wowarmory#154]
Hello Shadez
# i have problem with error

Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator, webmaster@www.www.com and inform them of the time the error occurred, and anything you might have done that may have caused the error.

More information about this error may be available in the server error log.
# Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

i unzip .htaccess but have problem

sorry for my bad english

thanks.

**Comment by kliver** [comment]
Easy, replace your .htacces (in armory dir)

AddDefaultCharset ISO-8859-1

RewriteEngine On

RewriteRule ^(.*).xml $1.php?%{QUERY_STRING}

# RSS Feed

RewriteRule character-feed.atom character-feed-atom.php?%{QUERY_STRING}

Options -Indexes

**Comment by SignFinder** [comment]
AllowOverride All in httpd.conf
