### ISSUE TITLE
Trinity Update

### ISSUE THREAD

**Issue by Jildor** [Shadez/wowarmory#155]
Please update changes: https://github.com/TrinityCore/TrinityCore/commit/ae3ab32ea5bf697a7b3f6d1fbc0740d7404d7c92

thx.

**Comment by SignFinder** [comment]
useless work involved TC developers

**Comment by Shadez** [comment]
Working on it, thank you!

**Comment by SignFinder** [comment]
в class.arenateams.php опечатка- "weekWeens" а нужно "weekWins"

**Comment by SignFinder** [comment]
и еще одна ошибка-не разобрался с налету :-(
<strong>DEBUG</strong> [11-04-2011 13:34:43]: ArmoryDatabaseHandler::_query : unable to execute SQL query (
                        SELECT
                        `arena_team`.`arenaTeamId` AS `arenateamid`,
                        `arena_team`.`name`,
                        `arena_team_stats`.`rating`,
                        `arena_team_stats`.`weekGames`   AS `gamesPlayed`,
                        `arena_team_stats`.`weekWins`    AS `gamesWon`,
                        `arena_team_stats`.`rank`        AS `ranking`,
                        `arena_team_stats`.`seasonGames` AS `seasonGamesPlayed`,
                        `arena_team_stats`.`seasonWins`  AS `seasonGamesWon`,
                        `characters`.`race`
                        FROM `arena_team` AS `arena_team`
                        LEFT JOIN `arena_team_stats` AS `arena_team_stats` ON `arena_team_stats`.`arenateamid`=`arena_team`.`arenaTeamId`
                        LEFT JOIN `characters` AS `characters` ON `characters`.`guid`=`arena_team`.`captainGuid`
                        WHERE `arena_team`.`type`=2 AND `arena_team_stats`.`rank` > 0
                        ORDER BY rank ASC LIMIT 0, 20). MySQL error: "Unknown column 'arena_team_stats.weekGames' in 'field list'" (Error #1054)<br />

**Comment by SignFinder** [comment]
по последнему разобрался-таблицы arena_team_stats нет больше в тринити-все данные в arena_team перенесены
