### ISSUE TITLE
Chrome SERIOUS bug with tooltip

### ISSUE THREAD

**Issue by maximgeerinck** [Shadez/wowarmory#159]
hi

so whenever i use chrome none of the tooltips work like
- char page and items (solved by using wowhead -.-)
- Talent calc
  -others doesnt work either

please fix this if you can thx
greetings c4d3r

**Comment by Shadez** [comment]
It's a JavaScript issue which I can't handle, sorry. I need someone who can fix JS code...
But on Chrome 10.0.648.204 talent calculator works fine for me.

**Comment by maximgeerinck** [comment]
i hope this gets fixed some time :s

**Comment by maximgeerinck** [comment]
OK i have found the problem

its giving problems with the part where it is caching the tooltip in the browser 

if(($.browser.safari) || ($.browser.safari)){
                toolVault[itemUrl] = msg;

```
            if(toolVault[itemUrl].length <= 4)
                toolVault[itemUrl] = errorLoadingToolTip;
        }else{
            var bufferedDiv = document.createElement("div");
            bufferedDiv.innerHTML = "";
            bufferedDiv.appendChild(xsltProcessor.transformToFragment(msg,window.document));                    
            toolVault[itemUrl] = bufferedDiv.innerHTML;

            //set error message
            if(toolVault[itemUrl].length <= 4)
                toolVault[itemUrl] = errorLoadingToolTip;                   
        }
    },
    error: function(msg){               
        toolVault[itemUrl] = errorLoadingToolTip;
    }
});
```

When i try the armory.js from the original armory then it sais error loading tooltip the error is then at this part but u are probabbly caching wrong tooltips which makes it not working in chrome because it stops on error validation
