### ISSUE TITLE
Viewer on armory

### ISSUE THREAD

**Issue by Vasago** [Shadez/wowarmory#16]
Because of lack of models from newest items and nobody knows how to get them it would be better t use wowhead viewer i think is it possible? http://www.trinitycore.org/forum/character-3d-preview-t7108.html?t=7108 here is preview

**Comment by Shadez** [comment]
It's possible and you can write patch for it but I'm wouldn't add Wowhead viewer in armory.

**Comment by Vasago** [comment]
So it is better to have not complete and not fully functional viewer than fully working from wowhead? Can you write this patch as alternative solution please? I dont know how to do that thx :-)

**Comment by Shadez** [comment]
From the users side, yes, Wowhead viewer is more better, but from my point of view it's not good because Wowhead is not any part of WoWArmory and I want to bring the armory as close as possible to the original.
