### ISSUE TITLE
Characters aren't recongized by the system.

### ISSUE THREAD

**Issue by zze** [Shadez/wowarmory#167]
Everything is functioning for the most part; Except when logging into an account it'll say this account has no characters yet.
If I select "More characters" from the account emblem, I'll see my character but upon selecting a character I receive this error message:
#### File Not Found

```
This character profile could not be displayed, possibly for one of the following reasons:

* The character has been inactive for an extended period of time.
* The character name was spelled incorrectly.
* The profile is temporarily unavailable while the character is in the midst of a process such as a realm transfer or faction change.
* Characters that have been deleted are no longer available on the Armory. ")

```

I've:
*Imported and updated the `armory` database.
*Patched TrinityCore based off given patch file & recompiled.
*Triple checked everything, including the configuration file.

Any ideas? is this problem for everyone?

**Comment by SOWRON** [comment]
I have the same problem. I can not understand what was happening. Settings are correct. 10 times all rechecked.

**Comment by ghost** [comment]
Same problem here aswell..

**Comment by snehurka324** [comment]
BUMP?!

**Comment by azovez** [comment]
Same problem bump help plz

**Comment by azovez** [comment]
bump

**Comment by jjhidalgar** [comment]
bump

same with trinity 3.3.5a set conf dbs as
auth
characters
world

**Comment by zze** [comment]
This project is no longer supported.
