### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by raspotidza** [Shadez/wowarmory#172]
Hi all I've this issues I can't resolve

Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.
Please contact the server administrator, admin@localhost and inform them of the time the error occurred, and anything you might have done that may have caused the error.
More information about this error may be available in the server error log.
Additionally, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle the request.
Apache/2.2.6 (Win32) DAV/2 mod_ssl/2.2.6 OpenSSL/0.9.8e mod_autoindex_color PHP/5.2.4 Server at www.carthagods-servers.com Port 80

I've replaced .htaccess by the new one that kliver have posted for this post https://github.com/Shadez/wowarmory/issues/154
by 

AddDefaultCharset ISO-8859-1
RewriteEngine On
RewriteRule ^(.*).xml $1.php?%{QUERY_STRING}
RSS Feed
RewriteRule character-feed.atom character-feed-atom.php?%{QUERY_STRING}
Options -Indexes

but I've the same problem

This is my apatche error log

[Thu Oct 20 15:15:37 2011] [alert] [client 197.28.179.134] C:/Users/Administrator/Desktop/carthagods servers/_Server/htdocs/armory/.htaccess: Invalid command 'RewriteEngine', perhaps misspelled or defined by a module not included in the server configuration, referer: http://www.carthagods-servers.com/index.php?terms=agree

Please need help.
And sory for my bad english ;)

**Comment by Shadez** [comment]
You need to add/install/enable mod_rewrite module for Apache HTTPD Server

**Comment by raspotidza** [comment]
Thanks for quick answer,
I've enable mod_rewrite module for Apache in HTTPD.conf
LoadModule rewrite_module modules/mod_rewrite.so

and i've allowd  AllowOverride
<Directory />
    Options FollowSymLinks
    AllowOverride All
    Order deny,allow
    Deny from all
</Directory>
<Directory "../_Server/htdocs">
    Options Indexes FollowSymLinks Includes ExecCGI
    AllowOverride All
    Order allow,deny
    Allow from all
</Directory>

The 500 Internal Server Error hase been fexed, but i've other Issue
when i load the directory of armory 

http://myhost/armory

then nothing happen, and i've seen in the source code
i've this error 

Unknown: open(..\tmp\sess_ef1ad6c1c760142d91f803dc87d21840, O_RDWR) failed: No such file or directory
Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct

Can you help me again Shadez please?
