### ISSUE TITLE
Arena Emblem Colors

### ISSUE THREAD

**Issue by gyullo** [Shadez/wowarmory#20]
Here is a fix, at least in trinity the arena emblem colors are bad real bad, a lot of pinks :P
Well with this, the right color is shown in ladder or a specific team sheet:

Just change this function like this:
[code]    public function GetArenaTeamEmblem($teamId = null, $db = false) {
        if($teamId == null) {
            $teamId = $this->arenateamid;
        }
        if($db == false) {
            $arenaTeamEmblem = $this->cDB->selectRow("
            SELECT `BackgroundColor` AS `background`, `BorderColor` AS `borderColor`, `BorderStyle` AS `borderStyle`, `EmblemColor` AS `iconColor`, `EmblemStyle` AS `iconStyle`
                FROM `arena_team`
                    WHERE `arenateamid`=?", $teamId);
            $arenaTeamEmblem['background'] = dechex($arenaTeamEmblem['background']);
            $arenaTeamEmblem['borderColor'] = dechex($arenaTeamEmblem['borderColor']);
            $arenaTeamEmblem['iconColor'] = dechex($arenaTeamEmblem['iconColor']);
            return $arenaTeamEmblem;
        }
        else {
            $arenaTeamEmblem = $db->selectRow("
            SELECT `BackgroundColor` AS `background`, `BorderColor` AS `borderColor`, `BorderStyle` AS `borderStyle`, `EmblemColor` AS `iconColor`, `EmblemStyle` AS `iconStyle`
                FROM `arena_team`
                    WHERE `arenateamid`=?", $teamId);
            $arenaTeamEmblem['background'] = dechex($arenaTeamEmblem['background']);
            $arenaTeamEmblem['borderColor'] = dechex($arenaTeamEmblem['borderColor']);
            $arenaTeamEmblem['iconColor'] = dechex($arenaTeamEmblem['iconColor']);
            return $arenaTeamEmblem;
        }
    }[/code]

**Comment by Shadez** [comment]
In 230 rev., thank you!
