### ISSUE TITLE
Problem with achievements in feed (recent activity)

### ISSUE THREAD

**Issue by Vasago** [Shadez/wowarmory#22]
When i see character profile there are always achievements in Recent Activity like http://www.wowhead.com/achievement=116 or http://www.wowhead.com/achievement=892 or http://www.wowhead.com/achievement=133 etc every day are shown on character profile as "today completion" but these achievements were mostly done in very past. (Trinity core) Others recent activities are shown correctly but these achievements not.

In debug mode there are no errors about this - so maybe bad DB data? I have [239] and only these errors:
Characters::GetCharacterItemInfo : unable to get item_id for player 31945 (Igi); slotid is tabard
Characters::GetCharacterItemInfo : unable to get item_id for player 31945 (Igi); slotid is shirt

**Comment by Shadez** [comment]
Need some code rewrites. Closed as known bug, but anyway, thank you.
