### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ghost** [Shadez/wowarmory#24]
Когда я использую поиск по армори выдаёт ошибку:

Ошибка синтаксического анализа XML: лишние данные после элемента документа
Адрес: http://10.6.22.180/wowarmory/arena-ladder.xml?ts=3&b=Massive+Network
Строка 2, символ 1:<b>Warning</b>:  mysql_errno() expects parameter 1 to be resource, boolean given in <b>C:\system\htdocs\wowarmory\includes\classes\libs\DbSimple\Mysql.php</b> on line <b>184</b><br />

Я использую xampp 1.7.3
Apache 2.2.14 (IPV6 enabled)
MySQL 5.1.41 (Community Server) with PBXT engine 1.0.09-rc
PHP 5.3.1 (PEAR, Mail_Mime, MDB2, Zend)
Армори r232 для trinity 3.3.3a

**Comment by Eulogy** [comment]
Confirm, firefox, IExplorer & Chrome.

**Comment by Shadez** [comment]
Read F.A.Q. section in http://getmangos.com/community/showthread.php?12096-World-of-Warcraft-Armory
