### ISSUE TITLE
XML Parsing Error

### ISSUE THREAD

**Issue by xpzz** [Shadez/wowarmory#28]
At search a character or arena team appears this error:

---

XML Parsing Error: junk after document element
Location: http://www.modworldserver.com.br/armory/search.xml?searchQuery=nanzera&searchType=all
Line Number 2, Column 1:<b>Warning</b>:  mysql_errno(): supplied argument is not a valid MySQL-Link resource in <b>/var/www/armory/includes/classes/libs/DbSimple/Mysql.php</b> on line <b>184</b><br />
## ^

example:
http://www.modworldserver.com.br/armory/search.xml?searchQuery=nanzera&searchType=all

how to fix this?

**Comment by Shadez** [comment]
Read F.A.Q section before posting new issue. This error was already discussed in other issues and commit comments.

**Comment by xpzz** [comment]
Sorry i found the error and fixed this... but when i search for a char now i recieve this message: 

File Not Found
This character profile could not be displayed, possibly for one of the following reasons:

```
* The character has been inactive for an extended period of time.
* The character name was spelled incorrectly.
* The profile is temporarily unavailable while the character is in the midst of a process such as a realm transfer or faction change.
* Characters that have been deleted are no longer available on the Armory.
```

**Comment by Shadez** [comment]
Please, read WHOLE FAQ before posting. There's already info about this error too.
