### ISSUE TITLE
On Trinitycore 3D Models are nude

### ISSUE THREAD

**Issue by 3kynox** [Shadez/wowarmory#30]
Armory 249

After having installed DB updated.

http://img99.imageshack.us/i/mind.jpg/

**Comment by Shadez** [comment]
Look at FAQ section in project thread on getmangos.com - i've just updated info about naked models.

**Comment by ghost** [comment]
I am using windows OS and how do I solve this problem?
FAQ on getmangos.com useless.

**Comment by Shadez** [comment]
> \xf0\x94\xf1\x80\xf0\xb5\xf0\xbd\xf0\xb5\xf0\xb8

very odd paths. Look at your charset config in apache

**Comment by Shadez** [comment]
> But why trys the modelviewer to use files which have no name ?

Something wrong with character-model.xml. I've added file_exists() checks to generation but seems its not working.

> I use UTF-8 as default charset for system and apache2.

Open character-model.xml?r=REALM&cn=CHARNAME and look at the paths. They have similar letters (\xf0\x94\xf1\x80\xf0)?

**Comment by sprokopiev** [comment]
my error logs
armory debug
<strong>DEBUG</strong> [07-07-2010 09:53:49]: Characters::BuildCharacter : All correct, player Perrin builded<br />
<strong>DEBUG</strong> [07-07-2010 09:53:49]: Characters::GetCharacterItemInfo : unable to get item_id for player 47 (Perrin)
<strong>DEBUG</strong> [07-07-2010 09:53:51]: Characters::BuildCharacter : All correct, player Perrin builded<br />
<strong>DEBUG</strong> [07-07-2010 09:53:51]: Utils::IsAccountHaveCurrentCharacter : session not found<br />

Apache error log

10.0.0.2 - - [07/Jul/2010:12:22:32 +0300] "GET /wowarmory/ HTTP/1.1" 200 220 "-" "Mozilla/5.0 (Windows; U; Windows NT 5.1; en
10.0.0.2 - - [07/Jul/2010:12:22:32 +0300] "GET /wowarmory/_layout/nav/user-menu.xsl HTTP/1.1" 304 - "http://10.0.0.100/wowarm
10.0.0.2 - - [07/Jul/2010:12:22:32 +0300] "GET /wowarmory/_layout/nav/bookmarks.xsl HTTP/1.1" 304 - "http://10.0.0.100/wowarm
10.0.0.2 - - [07/Jul/2010:12:22:32 +0300] "GET /wowarmory/_content/en_gb/strings.xml HTTP/1.1" 200 168758 "http://10.0.0.100/
10.0.0.2 - - [07/Jul/2010:12:22:33 +0300] "GET /wowarmory/battlegroups.php HTTP/1.1" 200 422 "http://10.0.0.100/wowarmory/" "
10.0.0.2 - - [07/Jul/2010:12:22:33 +0300] "GET /wowarmory/_content/_region/eu/links.xml HTTP/1.1" 200 226 "http://10.0.0.100/
10.0.0.2 - - [07/Jul/2010:12:22:33 +0300] "GET /wowarmory/login-status.php HTTP/1.1" 200 139 "http://10.0.0.100/wowarmory/" "
10.0.0.2 - - [07/Jul/2010:12:22:33 +0300] "GET /wowarmory/_layout/nav/menu.xml HTTP/1.1" 200 12810 "http://10.0.0.100/wowarmo
10.0.0.2 - - [07/Jul/2010:12:22:33 +0300] "GET /wowarmory/_content/en_gb/ri-armory.xml HTTP/1.1" 200 4069 "http://10.0.0.100/
10.0.0.2 - - [07/Jul/2010:12:22:33 +0300] "GET /wowarmory/newsfeed.xml?loc=en_gb HTTP/1.1" 404 220 "http://10.0.0.100/wowarmo
10.0.0.2 - - [07/Jul/2010:12:22:33 +0300] "GET /wowarmory/_content/en_gb/achievements_feed.xml HTTP/1.1" 200 10570 "http://10
10.0.0.2 - - [07/Jul/2010:12:22:33 +0300] "GET /wowarmory/data/languages.xml HTTP/1.1" 200 434 "http://10.0.0.100/wowarmory/"
10.0.0.2 - - [07/Jul/2010:12:22:46 +0300] "GET /wowarmory/character-model.xml?r=REALM&cn=CHARNAME HTTP/1.1" 404 227 "-" "Mozi
10.0.0.2 - - [07/Jul/2010:12:22:46 +0300] "GET /favicon.ico HTTP/1.1" 404 209 "-" "Mozilla/5.0 (Windows; U; Windows NT 5.1; e
10.0.0.2 - - [07/Jul/2010:12:22:58 +0300] "GET /wowarmory/character-model.php?r=REALM&cn=CHARNAME HTTP/1.1" 200 211 "-" "Mozi
10.0.0.2 - - [07/Jul/2010:12:22:58 +0300] "GET /favicon.ico HTTP/1.1" 404 209 "-" "Mozilla/5.0 (Windows; U; Windows NT 5.1; e
10.0.0.2 - - [07/Jul/2010:12:23:10 +0300] "GET /wowarmory/character-model.php?r=Test&cn=CHARNAME HTTP/1.1" 200 211 "-" "Mozil
10.0.0.2 - - [07/Jul/2010:12:23:10 +0300] "GET /favicon.ico HTTP/1.1" 404 209 "-" "Mozilla/5.0 (Windows; U; Windows NT 5.1; e
10.0.0.2 - - [07/Jul/2010:12:23:16 +0300] "GET /wowarmory/character-model.php?r=Test&cn=Perrin HTTP/1.1" 200 211 "-" "Mozilla
10.0.0.2 - - [07/Jul/2010:12:23:16 +0300] "GET /favicon.ico HTTP/1.1" 404 209 "-" "Mozilla/5.0 (Windows; U; Windows NT 5.1; e
10.0.0.2 - - [07/Jul/2010:12:23:23 +0300] "GET /wowarmory/character-model.php HTTP/1.1" 200 211 "-" "Mozilla/5.0 (Windows; U;
10.0.0.2 - - [07/Jul/2010:12:23:23 +0300] "GET /favicon.ico HTTP/1.1" 404 209 "-" "Mozilla/5.0 (Windows; U; Windows NT 5.1; e

**Comment by Shadez** [comment]
I don't see any useful info for me in this log.

**Comment by dgoujard** [comment]
i have also this bug, naked, in character-model.xml
http://gist.github.com/468295

**Comment by Shadez** [comment]
> http://gist.github.com/468295

Update to [306], disable cache, enable debug log (if disabled), copy-paste new XML data from character-model and full debug log from http://armoryurl/cache/_debug/.

I have an idea but I need a confirmation for it.
Thanks.

**Comment by stampis** [comment]
From debug-file;

<strong>ERROR</strong> [12-07-2010 20:40:22]: Items::GetItemModelData : unable to get model data for displayID 12864 (row: texture_2, itemid: 2579)<br />
<strong>ERROR</strong> [12-07-2010 20:40:22]: Items::GetItemModelData : unable to get model data for displayID 55983 (row: visual_3, itemid: 44198)<br />
<strong>ERROR</strong> [12-07-2010 20:40:22]: Items::GetItemModelData : unable to get model data for displayID 64847 (row: visual_1, itemid: 49808)<br />
<strong>ERROR</strong> [12-07-2010 20:40:22]: Items::GetItemModelData : unable to get model data for displayID 53132 (row: visual_1, itemid: 44183)<br />
<strong>ERROR</strong> [12-07-2010 20:40:22]: Items::GetItemModelData : unable to get model data for displayID 54075 (row: visual_4, itemid: 41116)<br />
<strong>ERROR</strong> [12-07-2010 20:40:22]: Items::GetItemModelData : unable to get model data for displayID 64722 (row: visual_5, itemid: 49794)<br />
<strong>ERROR</strong> [12-07-2010 20:40:22]: Items::GetItemModelData : unable to get model data for displayID 64721 (row: visual_7, itemid: 49795)<br />
<strong>ERROR</strong> [12-07-2010 20:40:22]: Items::GetItemModelData : unable to get model data for displayID 55943 (row: modelTexture_1, itemid: 44188)<br />
<strong>ERROR</strong> [12-07-2010 20:40:22]: Items::GetItemModelData : unable to get model data for displayID 51577 (row: modelName_1, itemid: 43184)<br />
<strong>ERROR</strong> [12-07-2010 20:40:22]: Items::GetItemModelData : unable to get model data for displayID 57334 (row: modelName_1, itemid: 44735)<br />
<strong>ERROR</strong> [12-07-2010 20:40:22]: Items::GetItemModelData : unable to get model data for displayID 52178 (row: modelName_1, itemid: 41113)<br />
<strong>ERROR</strong> [12-07-2010 20:40:22]: Items::GetItemModelData : unable to get model data for displayID 52178 (row: modelName_1, itemid: 41113)<br />
<strong>ERROR</strong> [12-07-2010 20:40:22]: Items::GetItemModelData : unable to get model data for displayID 52178 (row: modelTexture_1, itemid: 41113)<br />

**Comment by dgoujard** [comment]
Debug file : https://gist.github.com/5eb03835a2d1c751fc55
Xml file : https://gist.github.com/426359594533f8788d36

**Comment by Shadez** [comment]
Sorry, it was my fault :( I forgot to add `armory_itemdisplayinfo` table in latest full SQL dump. Provided update in [307] should fix this problem.

**Comment by stampis** [comment]
Works now.. but 1 bug...
If a character wears a Shirt + Chest peice the Shirt will overlap the Robe/Chest (main armory).. Looks really funny..

http://img704.imageshack.us/img704/1075/shirtpowa.jpg

If a chest is equiped it should have priority over Shirt ;)
(Also Armory dont show helm for some reason, even if the character have ShowHelm enabled..)

**Comment by sprokopiev** [comment]
After 308 sql update it works for me now,but not showing all the items that character wears.

Characters::BuildCharacter : All correct, player Admin builded<br />
Arenateams::GetCharacterArenaTeamInfo : player 420 does not have any arena teams<br />
Characters::GetCharacterItemInfo : unable to get item_id for player 420 (Admin); slotid is trinket1 (nothing equipped?)<br />
Characters::GetCharacterItemInfo : unable to get item_id for player 420 (Admin); slotid is trinket2 (nothing equipped?)<br />
Characters::GetCharacterItemInfo : unable to get item_id for player 420 (Admin); slotid is relic (nothing equipped?)<br />
Characters::GetCharacterItemInfo : unable to get item_id for player 420 (Admin); slotid is tabard (nothing equipped?)<br />
Characters::BuildCharacter : All correct, player Admin builded<br />

**Comment by dgoujard** [comment]
It's Ok for me. This debug log it's look like ok also, because you don't have all slots equipped on your character.

**Comment by dgoujard** [comment]
I have also this bug with tabard over Robe/Chest. And if i haven't tabard I'm shirtless. http://img821.imageshack.us/img821/2726/armu.jpg

**Comment by dgoujard** [comment]
Another bug, some race have size bug in 3D model, and you can't reduce size. http://emberapp.com/creatix/images/safari-14/ http://emberapp.com/creatix/images/safari-15/
