### ISSUE TITLE
Unable to find Data

### ISSUE THREAD

**Issue by sprokopiev** [Shadez/wowarmory#31]
I've install everything TrinityCore rev.8696 + patch for trinitycore + sql update and when i try to veiw character debug say:
"unable to find data for realmID 0"
Pls Help.

**Comment by sprokopiev** [comment]
i fix this problem but there is other problem
http://img339.imageshack.us/img339/9851/armoryr.jpg

**Comment by sprokopiev** [comment]
one more error when viewing items
"Error loading tooltip"

**Comment by Shadez** [comment]
> i fix this problem but there is other problem

Can't see any. If you're talking about missed icons, download icons archive.

> "Error loading tooltip"

Open item-tooltip.xml?i=itemID&cn=charName&r=realmName directly and show error.

**Comment by sprokopiev** [comment]
when i open :item-tooltip.xml?i=itemID&cn=charName&r=realmName directly it opens,but the error is here:
http://img690.imageshack.us/img690/242/armory2.jpg
i have upload icons in httpdocs/wow-icons/_images/

**Comment by Shadez** [comment]
> i have upload icons in httpdocs/wow-icons/_images/

Re-check paths to directory, you're doing something wrong.
PS What browser do you use?

**Comment by sprokopiev** [comment]
google chrome

**Comment by sprokopiev** [comment]
i allmost fix the problem only when loading 3d view loading freez

**Comment by sprokopiev** [comment]
10x for the help

**Comment by sprokopiev** [comment]
problem: 3d models are nude,but i know you are working on them.
Your project i great. 10x for every thing and keep the good work.

**Comment by Shadez** [comment]
If armory installed correctly and you've patched core/characters db with provided updates, model cannot be nude. Check and re-check every step you've done.
