### ISSUE TITLE
Armory Cleanup

### ISSUE THREAD

**Issue by eugene-matvejev** [Shadez/wowarmory#32]
Планируеться ли cделать cleanup в армори? т.е. вырезать рекламу не используемые языки убрать регионы и так далее? они вроде как не нужны :)
так сказать облегчить её

Например многие базы данных делают по принципу enGB locale + возможность залить какую надо пользователю или YTDB enGB+ruRU, возможо ли это сделать с этим армори?

**Comment by Shadez** [comment]
Рекламы там нет, только пустые блоки под неё. Некоторые языки кем-то используются, кем-то нет, так что убирать их под чистую не буду. Насчет локалей в SQL подумаю, но обновление каждого языка по отдельности занимает время, которое жалко на это тратить :) Но запросы в базу на удаление ненужных стобцов никто не отменял, вы можете это сделать и без моей помощи.
