### ISSUE TITLE
Joomla! Armory Extension

### ISSUE THREAD

**Issue by eugene-matvejev** [Shadez/wowarmory#33]
Будут ли разрабатываться дополнения для Joomla! для армори?

**Comment by Shadez** [comment]
Нет, но, думаю, подойдет какой-нибудь модуль для официальной Оружейной, т.к. структура XML практически идентичная. Но, возможно, понадобятся некоторые правки.

PS секция Issues создана для багрепортов, насколько я знаю. По таким вопросам можно писать в личку. Закрыто.
