### ISSUE TITLE
Icon pack ??

### ISSUE THREAD

**Issue by Matt-One** [Shadez/wowarmory#36]
Shadez Upload
"C:\fake_path\wow-icons_update_r276.7z" is at Shadez/wowarmory/downloads 
Icons Update (not full pack) for patch 3.3.5a

..but there is no file for 3.3.5....

**Comment by Shadez** [comment]
Icons archive was added directly to repository in <a href="http://github.com/Shadez/wowarmory/commit/af3643b1021d3d5989baea0a0b4b5f186462c05a">[276] rev.</a>. There's something wrong with GitHub uploader or with my browser =)

**Comment by Matt-One** [comment]
eheheheh thanks shadez you rock with this armory ;)
