### ISSUE TITLE
howto patch core?

### ISSUE THREAD

**Issue by 130ng0** [Shadez/wowarmory#39]
can anyone tell me how to patch the core in windows?
i searched in google but i didnt found anything :(

neeeed fast help please.

**Comment by 130ng0** [comment]
ok i found a howto

**Comment by webv2** [comment]
how ?

**Comment by 130ng0** [comment]
i searched in google many hours.
and then i found a german howto there:
http://forum.mmonerds.de/tutorials-14/trinity-core-compilen-linux-windows-68044/

**Comment by webv2** [comment]
omg , german xD Thank you .

**Comment by 130ng0** [comment]
but the howto didnt work with the newest rev of TC they removed some files which u need to compile and i dont know how i should compile the new rev :(
if u find a way please inform me...

greedz

**Comment by webv2** [comment]
sure thing =)

**Comment by 130ng0** [comment]
ok i found another guide.
i test it atm.
if it works i will post here!

**Comment by 130ng0** [comment]
the guid works :)
http://www.trinitycore.info/index.php?title=Howto_win_tc2

**Comment by webv2** [comment]
You win =D
