### ISSUE TITLE
Character profile don't work

### ISSUE THREAD

**Issue by Muglackh** [Shadez/wowarmory#4]
I can't load character profile. (rev. [160]) There is this error:
File Not Found
This character profile could not be displayed, possibly for one of the following reasons:
The character has been inactive for an extended period of time.
The character name was spelled incorrectly.
The profile is temporarily unavailable while the character is in the midst of a process such as a realm transfer or faction change.
Characters that have been deleted are no longer available on the Armory.

**Comment by Shadez** [comment]
I think it's solved now

**Comment by dgoujard** [comment]
i have also this error.

**Comment by overy** [comment]
confirm...

**Comment by dgoujard** [comment]
you have trinity core overy ?

**Comment by overy** [comment]
yes :X

**Comment by Shadez** [comment]
Read Install/FAQ.

**Comment by dirtykid** [comment]
i got same error.. i`ve patched then rebuild the source.. also updated the characters db with the sql file from the trinity folder and nothing.. still i get this error.. please help

**Comment by kresnik** [comment]
yes, im got the same error. Please fixed.

**Comment by maximgeerinck** [comment]
patch core from tools folder according if you have trinity or mangos

the SERVER_TRINITY and SERVER_MANGOS is giving some troubles i dont know if other people has this error

i fixed it by removing switches in php files (php knowledge required) 

also check ur cache/_debug log its quite helpfull

**Comment by Shadez** [comment]
What troubles? Note that SERVER_MANGOS and SERVER_TRINITY are constants and must be written without apostrophes (').
