### ISSUE TITLE
Character Talent error

### ISSUE THREAD

**Issue by dgoujard** [Shadez/wowarmory#41]
I have last release ( 308 ) and I have an error when i watch character talents 

<br />
<b>Fatal error</b>:  Using $this when not in object context in <b>/home/apache/wowarmory/includes/classes/class.utils.php</b> on line <b>415</b><br />

**Comment by Shadez** [comment]
Check after [309]

**Comment by dgoujard** [comment]
It's good ;) with firefox, other browser like safari show blank page but it's because safari don't like xml/xslt/javascript in the same page.

**Comment by Shadez** [comment]
Oh, so fast response =)
