### ISSUE TITLE
Search error.

### ISSUE THREAD

**Issue by dgoujard** [Shadez/wowarmory#42]
Yes, it's me again, when i search an character or item i have an error. 

<br />
<b>Fatal error</b>:  Call to undefined method SearchMgr::calculaterelevance() in <b>/home/apache/wowarmory/includes/classes/class.search.php</b> on line <b>836</b><br />

**Comment by Shadez** [comment]
Fixed in [310] rev., thank you!

**Comment by dgoujard** [comment]
Thank.
