### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by zozo1990** [Shadez/wowarmory#43]
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator, admin@localhost and inform them of the time the error occurred, and anything you might have done that may have caused the error.

More information about this error may be available in the server error log.

TrinityCore 3.3.3a Rev. 8313 + TDB

Don't Work program.

This Configuration.php

<?php

/**
- @package World of Warcraft Armory
- @version Release Candidate 1
- @revision 303
- @copyright (c) 2009-2010 Shadez  
- @license 

http://opensource.org/licenses/gpl-license.php GNU Public License
 *
- This program is free software; you can redistribute it and/or modify
- it under 

the terms of the GNU General Public License as published by
- the Free Software Foundation; either version 2 of the License, or
- (at your option) any 

later version.
 *
- This program is distributed in the hope that it will be useful,
- but WITHOUT ANY WARRANTY; without even the implied warranty of
- 

MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
- GNU General Public License for more details.
  *
- You should have received a copy of the 

GNU General Public License
- along with this program; if not, write to the Free Software
- Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  

02111-1307  USA
 **/

if(!defined('**ARMORY**')) {
    die('Direct access to this file not allowed!');
}

$ArmoryConfig = array();
$ArmoryConfig['mysql'] = 

array();
/\* Armory Database configuration */
$ArmoryConfig['mysql']['host_armory']     = 'localhost';
$ArmoryConfig['mysql']['user_armory']     = 'root';
$ArmoryConfig['mysql']['pass_armory']     = 'szabo1990';
$ArmoryConfig['mysql']['name_armory']     = 'armory';
$ArmoryConfig['mysql']['charset_armory']  = 

'UTF8';

/\* Accounts (realmd) Database configuration */
$ArmoryConfig['mysql']['host_realmd']         = 'localhost';
$ArmoryConfig['mysql']['user_realmd']  

```
   = 'root';
```

$ArmoryConfig['mysql']['pass_realmd']         = 'szabo1990';
$ArmoryConfig['mysql']['name_realmd']         = 'realmd';
$ArmoryConfig['mysql']['charset_realmd']      = 'UTF8';

/\* For characters & world DB configuration see $ArmoryConfig['multiRealm'][2]['*_characters'] / 

['*_mangos'] */

/\* Armory settings */
$ArmoryConfig['settings']['server_version']   = '333'; // '322' or '333', without dots or something else
$ArmoryConfig['settings']['siteCharset']      = 'utf-8';
$ArmoryConfig['settings']['useNews']          = false;
$ArmoryConfig['settings']['defaultRealmId'] 

  = 1;
$ArmoryConfig['settings']['defaultRealmName'] = 'trinity'; // Realm name
$ArmoryConfig['settings']['defaultBGName']    = 'Massive Network'; // 

"Battlegroup" name, just cosmetic
$ArmoryConfig['settings']['useCache']         = false;
$ArmoryConfig['settings']['cache_lifetime']   = 86400; // In 

seconds; default - 1 day.
$ArmoryConfig['settings']['minlevel']         = 10; // Character must have this level or higher to be shown in Armory
$ArmoryConfig['settings']['minGmLevelToShow'] = 3;  // Show characters : 0 - only players, 1 - moderators, 2 - GMs, 3 - everyone
$ArmoryConfig['settings']['defaultLocale']    = 'ru_ru'; // Can be 'ru_ru' or 'en_gb'
$ArmoryConfig['settings']['showScriptInfo']   = true;    // Display 

script info (generation time, etc.) ? (true/false) (not used now)
$ArmoryConfig['settings']['maintenance']      = false;   // Disable site? (true/false)
$ArmoryConfig['settings']['useDebug']         = false;   // Use debug? (true/false). STRONGLY not recommended on live server!
$ArmoryConfig['settings']['logLevel']         = 1;       // 1 - only errors, 2 - debug mode
$ArmoryConfig['settings']['configVersion']    = 1107201001; // 

Do not change this value!
$ArmoryConfig['settings']['checkVersionType'] = 'show'; // How to output Armory check results (db revision, config version, 

etc.)
                                                       // Option can have 'show' or 'log' value (if nothing selected, script will use 'show' value)

```
                                                 // 'show': display error message and stop script work


  // 'log' : write error to error log and continue script work (may cause errors!)
                                                   // Default 
```

and recommended value: 'show'

$ArmoryConfig['multiRealm'][1]['id']                 = 1;
$ArmoryConfig['multiRealm'][1]['name']               = 

'MaNGOS1';
$ArmoryConfig['multiRealm'][1]['type']               = 'mangos';
$ArmoryConfig['multiRealm'][1]['host_characters']    = 'localhost';
$ArmoryConfig['multiRealm'][1]['user_characters']    = 'root';
$ArmoryConfig['multiRealm'][1]['pass_characters']    = '';
$ArmoryConfig['multiRealm'][1]['name_characters']    = 'characters';
$ArmoryConfig['multiRealm'][1]['charset_characters'] = 'UTF8';
$ArmoryConfig['multiRealm'][1]['host_mangos']        = 'localhost';
$ArmoryConfig['multiRealm'][1]['user_mangos']        = 'root';
$ArmoryConfig['multiRealm'][1]['pass_mangos']        = '';
$ArmoryConfig['multiRealm'][1]['name_mangos']        = 'mangos';
$ArmoryConfig['multiRealm'][1]['charset_mangos']     = 'UTF8';

$ArmoryConfig['multiRealm'][2]['id']                 = 1;
$ArmoryConfig['multiRealm'][2]['name']               = 'trinity';
$ArmoryConfig['multiRealm'][2]['type']               = 'trinity';
$ArmoryConfig['multiRealm'][2]['host_characters']    = 'localhost';
$ArmoryConfig['multiRealm'][2]['user_characters']    = 'root';
$ArmoryConfig['multiRealm'][2]['pass_characters']    = 'szabo1990';
$ArmoryConfig['multiRealm'][2]['name_characters']    = 'characters';
$ArmoryConfig['multiRealm'][2]['charset_characters'] = 'UTF8';
$ArmoryConfig['multiRealm'][2]['host_mangos']        = 'localhost';
$ArmoryConfig['multiRealm'][2]['user_mangos']        = 'root';
$ArmoryConfig['multiRealm'][2]['pass_mangos']        = 'szabo1990';
$ArmoryConfig['multiRealm'][2]['name_mangos']        = 'world';
$ArmoryConfig['multiRealm'][2]['charset_mangos']     = 'UTF8';
?>

????

**Comment by Shadez** [comment]
Not Armory problem - wrong Apache configs.
