### ISSUE TITLE
отсутствующие модели

### ISSUE THREAD

**Issue by crAwling** [Shadez/wowarmory#44]
Отсутствует достаточно много моделей, например, прист в разгневанном сете или т10 полностью не прогружается, в дебаг логах само собой нечего, просто пишет о том, что создался чар успешно, в логах апача
[Thu Jul 15 11:00:39 2010] [error] [client 10.250.0.15] File does not exist: /server/www/htdocs/games/wow/wowarmory/models/item/texturecomponents/foottexture/robe_pvpwarlock_b_04_boot_fo_u.png, referer: http://site/wowarmory/models/flash/ModelViewer3.swf
[Thu Jul 15 11:00:39 2010] [error] [client 10.250.0.15] File does not exist: /server/www/htdocs/games/wow/wowarmory/models/item/objectcomponents/shoulder/lshoulder_cloth_pvppriest_b_04.m2, referer: http://site/wowarmory/models/flash/ModelViewer3.swf

модели с http://filekeeper.org/download/browser.php?path=shadez1%2Fwowarmory/ скачал, мб есть обновленные?

**Comment by Shadez** [comment]
Да, баг известный. На момент выкачивания моделей, на серверах Близзард не было а8 моделек и некоторых частей т10. Обновления пока что нет, всё руки не доходят сделать. Займусь, пожалуй, на след. неделе.

**Comment by crAwling** [comment]
Ясно, спасибо. Сообщите пожалуйста в коммите как обновите.
