### ISSUE TITLE
xml not found

### ISSUE THREAD

**Issue by gidsola** [Shadez/wowarmory#45]
I have installed everything I can find for xmlwriter, but no matter what I do I cannot make it generate the xml..

Main page displays fine, but any link or otherwise within returns file not found *.xml...

I am on ubuntu 10.04, apache2 with php5.
as I said above I cant find anything more to install involved with xmlwriter.

Is there some link or otherwise you can refer me too?
what do ou use, package name etc? apt-get install whatgoeshere??

Please help as i would like very much to use this armory feature.

**Comment by gidsola** [comment]
little update, i am using your latest revision from repo.

**Comment by dgoujard** [comment]
http://github.com/Shadez/wowarmory/issues/closed#issue/10

**Comment by Shadez** [comment]
> file not found *.xml...

Extract .htaccess files from htaccess.zip

**Comment by gidsola** [comment]
Finally got it this morning.
had to follow some infos found @
http://ubuntuforums.org/showthread.php?t=255556

I guess im still noobish :)
Thanx for quick replies guys. Thank you.
