### ISSUE TITLE
Arena history charts doesn't work for trinity 3.3.3a

### ISSUE THREAD

**Issue by frabul** [Shadez/wowarmory#47]
The core rev is the last for client 3.3.3a , of course the patches from your repository were added to the core. 
Problems:
1) In match history graph it says 'Games currently displayed:  of  4' for a team with 3 matches played and it doesn't display anything , if i click on view recent games or view complete season then the browser hangs.
2) under the graph in match history filters table it reports completely screwed up data  about new rating and net delta.
3)In opponent history for each match played it count it 2 times. For example if team A plays 1 match against team B  and A wins , the table will display that A played 2 matches against B , won 2 , lost 0 . Also the net delta is completely wrong.

Thanks

**Comment by gyullo** [comment]
Confirmed.
Sometimes show you the total new rating, instead of the rating gained.
