### ISSUE TITLE
File not Found / Charactersearch

### ISSUE THREAD

**Issue by eisregen1991** [Shadez/wowarmory#48]
hello,

i have a problem with the armory with trinitycore. When I search a Character, show the arsenal the char. This is not a problem, because i click on the char, come a error:

File Not Found
This character profile could not be displayed, possibly for one of the following reasons:

```
* The character has been inactive for an extended period of time.
* The character name was spelled incorrectly.
* The profile is temporarily unavailable while the character is in the midst of a process such as a realm transfer or faction change.
* Characters that have been deleted are no longer available on the Armory.
```

I have patch all, what in tools/trinitycore was and have batch the sql. I'm totally desperate. Can you help me? I know, this question was already here, because this had me not helped.

MfG eisregen1991

**Comment by Shadez** [comment]
Copy-paste debug log to http://paste2.org/

**Comment by eisregen1991** [comment]
what do you mean? sry I'm confused, because i have yesterday a rootcrash :-/
