### ISSUE TITLE
Xml Eror , Dupilate characters ... , Characters dont work

### ISSUE THREAD

**Issue by ghost** [Shadez/wowarmory#49]
Chyba parsování XML: Nesmysly za kořenovým prvkem dokumentu
Adresa: http://kmfwowserver.no-ip.org/armory/search.xml?searchQuery=sepoo&searchType=all
Číslo řádku 2, sloupec 1:<b>Warning</b>:  strtotime() [<a href='function.strtotime'>function.strtotime</a>]: It is not safe to rely on the system's timezone settings. You are _required_ to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected 'Europe/Paris' for '2.0/DST' instead in <b>C:\xampp\htdocs\armory\includes\classes\class.search.php</b> on line <b>969</b><br />
^

**Comment by Shadez** [comment]
Not Armory error.

**Comment by ghost** [comment]
Please help ....with this error

**Comment by Shadez** [comment]
Use Google.
http://forum.joomla.org/viewtopic.php?p=1807264
