### ISSUE TITLE
Not all items are shown

### ISSUE THREAD

**Issue by sprokopiev** [Shadez/wowarmory#52]
For me everything works just perfect, but helm and cloak don't show.
http://a.imageshack.us/img84/8320/armoryc.jpg
My debug log is empty
Sorry for my bad English, i'm bulgarian.

**Comment by Shadez** [comment]
Enable cloak/helm displaying in game

**Comment by burnham** [comment]
I have download wow-icons_r308_full.7z and uncompress it in /var/www/wow-icons but still I can not see items in the list as you can see here http://armeria.adictoswow.com/character-sheet.xml?r=AdictosWoW+3.3.5a&cn=Balttasor Thanks for your answer and very nice work

**Comment by Shadez** [comment]
> I have download wow-icons_r308_full.7z and uncompress it in /var/www/wow-icons but still I can not see items in the list as you can see here

Look at your Apache error log for 404 errors and check icons path.

**Comment by sprokopiev** [comment]
I have a little problem after update
http://a.imageshack.us/img708/6439/errorpn.jpg
This is shown when i try to access a character profile.

**Comment by Shadez** [comment]
Create new paste at http://paste2.org with source XML code of character-sheet.xml page

**Comment by sprokopiev** [comment]
http://intoxicated-wow.co.cc/armory/character-sheet.php?r=Intoxicated`s&cn=Larisa

http://paste2.org/p/941264

**Comment by sprokopiev** [comment]
for me is fixed after 350 10x Shadez for your great work
