### ISSUE TITLE
Error with 344

### ISSUE THREAD

**Issue by Vasago** [Shadez/wowarmory#53]
Here is my error:
<b>Catchable fatal error</b>:  Argument 2 passed to Achievements::InitAchievements() must be an instance of ArmoryDatabaseHandler, boolean given, called in /var/www/wowarmory/includes/classes/class.characters.php on line 679 and defined in <b>/var/www/wowarmory/includes/classes/class.achievements.php</b> on line <b>75</b><br />

**Comment by Shadez** [comment]
Check mysql connection configs

**Comment by Vasago** [comment]
It should be ok ,,, i have following:

SELECT
            `armory_races`.`name_en_us` AS `race`,
            `armory_classes`.`name_en_us` AS `class`
            FROM `armory_races` AS `armory_races`
            LEFT JOIN `armory_classes` AS `armory_classes` ON `armory_classes`.`id`=5
            WHERE `armory_races`.`id`=10). MySQL error: none<br />
<strong>ERROR</strong> [05-08-2010 17:49:06]: Characters::BuildCharacter : unable to find class/race text strings for player

I dont have in DB name_en_us i used full and updates correctly.

**Comment by Vasago** [comment]
SELECT CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`data`, ' ', 29), ' ', '-1') AS UNSIGNED)  
                FROM `item_instance` 
                    WHERE `owner_guid`=70 AND `guid`=2222). MySQL error: Unknown column 'data' in 'field list'
There is no data in trinity core now.

**Comment by Shadez** [comment]
> There is no data in trinity core now.

I need SQL dump at least for 1 item with gems and enchantments on it to make it works with latest DB changes.

**Comment by Vasago** [comment]
INSERT INTO `item_instance` (`guid`, `owner_guid`, `creatorGuid`, `giftCreatorGuid`, `count`, `duration`, `charges`, `flags`, `enchantments`, `randomPropertyId`, `durability`, `playedTime`, `text`) VALUES
(152884, 2222, 0, 0, 1, 0, '0 0 0 0 0 ', 32769, '3873 0 0 0 0 0 3558 0 0 3533 0 0 0 0 0 2770 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ', 0, 68, 126489, '');

Item http://www.wowhead.com/item=41864
Enchant http://www.wowhead.com/spell=56034
Red gem http://www.wowhead.com/item=40151
Blue gem http://www.wowhead.com/item=40120/

**Comment by Shadez** [comment]
> This same on MaNGOS

At first, fix this errors:

> ERROR [06-08-2010 11:01:08]: Utils::CheckConfigRealmData : realm data for realm "WoWall" was not added to `armory_realm_data` table. Please, execute this query manually: "REPLACE INTO `armory_realm_data` (`id`, `name`) VALUES (1, 'WoWall');"
> ERROR [06-08-2010 11:01:08]: Utils::IsRealm : unable to find id for realm WoWall (armory_realm_data)
> DEBUG [06-08-2010 11:01:08]: Characters::BuildCharacter : realmId not provided!

And after this check character sheet again.

**Comment by Vasago** [comment]
Fixed thanks it was due to en_us instead en_gb in config

Seems ok now in latest - but still this bug is present i dont know why "know" bugs are closed when they are not fixed http://github.com/Shadez/wowarmory/issues/closed#issue/22

Also item_instance is still not ok and gems are not shown in armory.

**Comment by Shadez** [comment]
> Also item_instance is still not ok and gems are not shown in armory.

Try after 347 rev.

> why "know" bugs are closed when they are not fixed

Because I don't need reports about it - it's already known

**Comment by Vasago** [comment]
Fixed
