### ISSUE TITLE
armory not load

### ISSUE THREAD

**Issue by overy** [Shadez/wowarmory#56]
hello, after update to rev 348+ have problem with run amory...Debug log is empy

Deprecated: Function eregi() is deprecated in C:\xampp\htdocs\armory\includes\classes\class.dbhandler.php on line 191

Deprecated: Function eregi() is deprecated in C:\xampp\htdocs\armory\includes\classes\class.dbhandler.php on line 191

Deprecated: Function eregi() is deprecated in C:\xampp\htdocs\armory\includes\classes\class.dbhandler.php on line 191

Deprecated: Function eregi() is deprecated in C:\xampp\htdocs\armory\includes\classes\class.dbhandler.php on line 191

Deprecated: Function eregi() is deprecated in C:\xampp\htdocs\armory\includes\classes\class.dbhandler.php on line 191

Deprecated: Function eregi() is deprecated in C:\xampp\htdocs\armory\includes\classes\class.dbhandler.php on line 191

Warning: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\armory\includes\classes\class.dbhandler.php:191) in C:\xampp\htdocs\armory\index.php on line 29

**Comment by Shadez** [comment]
Hello, this errors should be fixed after [351] revision.

**Comment by overy** [comment]
fixed, thanks
