### ISSUE TITLE
No search Results

### ISSUE THREAD

**Issue by Nemeses** [Shadez/wowarmory#6]
As the title says, whenever i search for something, this message displays

Your search did not produce any results. To ensure that you're searching by parameters allowed by the Armory, make sure to:

```
* Only search for the categories currently in the Armory: items, characters, arena teams, guilds, and factions.
* Search by name only.
```

**Comment by Nemeses** [comment]
Ive updated the armory too

**Comment by Shadez** [comment]
Re-check your SQL connection info (includes/classes/configuration.php) - maybe you wrote wrong password(s) or DB name(s)?

**Comment by Nemeses** [comment]
nope, those are all good. just reInjected the SQL, still nothing.

**Comment by Nemeses** [comment]
If it helps, im using a Trinity Core, though im sure it will work still.

**Comment by Shadez** [comment]
Trinity Core is not supported :(

**Comment by Nemeses** [comment]
wow... that... a let down?
sorry for that?
do you know where i can get one for Trinity?
