### ISSUE TITLE
Compile error on trinitycore

### ISSUE THREAD

**Issue by sprokopiev** [Shadez/wowarmory#60]
[ 14%] Building CXX object src/server/game/CMakeFiles/game.dir/Battlegrounds/ArenaTeam.cpp.o
[ 14%] Building CXX object src/server/game/CMakeFiles/game.dir/Battlegrounds/Battleground.cpp.o
/usr/home/darkvader/install/trinitycore/src/server/game/Battlegrounds/Battleground.cpp: In member function 'void Battleground::EndBattleground(uint32)':
/usr/home/darkvader/install/trinitycore/src/server/game/Battlegrounds/Battleground.cpp:737: error: 'BattleGroundScoreMap' has not been declared
/usr/home/darkvader/install/trinitycore/src/server/game/Battlegrounds/Battleground.cpp:737: error: expected `;' before 'itr'
/usr/home/darkvader/install/trinitycore/src/server/game/Battlegrounds/Battleground.cpp:737: error: 'itr' was not declared in this scope
/usr/home/darkvader/install/trinitycore/src/server/game/Battlegrounds/Battleground.cpp:739: error: 'objmgr' was not declared in this scope
**\* Error code 1

This is after "wowarmory_arena_chart.patch"

**Comment by SignFinder** [comment]
objmgr -> sObjectMgr

**Comment by Shadez** [comment]
> objmgr -> sObjectMgr

Changed in [358], thank you!

@sprokopiev: try to compile again ;)

**Comment by SignFinder** [comment]
BattleGroundScoreMap -> BattlegroundScoreMap

**Comment by SignFinder** [comment]
BattleGround -> Battleground

**Comment by SignFinder** [comment]
GetBattleGround -> GetBattleground
this commit in trinity http://code.google.com/p/trinitycore/source/detail?spec=svnccb5ddead02d37df9ac9b8be749ba6e1d9001238&r=25256ac5c90fc4a51707a206da3731f2cd0ad0f3

**Comment by sprokopiev** [comment]
[ 14%] Building CXX object src/server/game/CMakeFiles/game.dir/Battlegrounds/Bat                                             tleground.cpp.o
/home/darkvader/install/trinitycore/src/server/game/Battlegrounds/Battleground.c                                             pp: In member function 'void Battleground::EndBattleground(uint32)':
/home/darkvader/install/trinitycore/src/server/game/Battlegrounds/Battleground.c                                             pp:737: error: 'BattleGroundScoreMap' has not been declared
/home/darkvader/install/trinitycore/src/server/game/Battlegrounds/Battleground.c                                             pp:737: error: expected `;' before 'itr'
/home/darkvader/install/trinitycore/src/server/game/Battlegrounds/Battleground.c                                             pp:737: error: 'itr' was not declared in this scope
/home/darkvader/install/trinitycore/src/server/game/Battlegrounds/Battleground.c                                             pp:739: error: 'objmgr' was not declared in this scope
/home/darkvader/install/trinitycore/src/server/game/Battlegrounds/Battleground.c                                             pp: In member function 'virtual void Battleground::UpdatePlayerScore(Player_, ui                                             nt32, uint32, bool)':
/home/darkvader/install/trinitycore/src/server/game/Battlegrounds/Battleground.c                                             pp:1367: error: 'SCORE_DAMAGE_TAKEN' was not declared in this scope
/home/darkvader/install/trinitycore/src/server/game/Battlegrounds/Battleground.c                                             pp:1368: error: 'class BattlegroundScore' has no member named 'DamageTaken'
/home/darkvader/install/trinitycore/src/server/game/Battlegrounds/Battleground.c                                             pp:1370: error: 'SCORE_HEALING_TAKEN' was not declared in this scope
/home/darkvader/install/trinitycore/src/server/game/Battlegrounds/Battleground.c                                             pp:1371: error: 'class BattlegroundScore' has no member named 'HealingTaken'
gmake[2]: *_\* [src/server/game/CMakeFiles/game.dir/Battlegrounds/Battleground.cp                                             p.o] Error 1
gmake[1]: **\* [src/server/game/CMakeFiles/game.dir/all] Error 2
gmake: **\* [all] Error 2

**Comment by SignFinder** [comment]
sprokopiev - rename BattleGroundScoreMap to BattlegroundScoreMap and other-read my old comments

**Comment by sprokopiev** [comment]
10x it helps me.trinity core compiles just perfect

**Comment by sprokopiev** [comment]
10x
