### ISSUE TITLE
Achievements::InitAchievements() error

### ISSUE THREAD

**Issue by yavor76** [Shadez/wowarmory#62]
Hi all !
I have some errors on new installed wowarmory. Is wowarmory compatible to work with last versions of Mangos, because I'm getting error: "Argument 2 passed to Achievements::InitAchievements() must be an instance of ArmoryDatabaseHandler, null given... class.characters.php on line 674".
I installed the 3 patch files to the Mangos core and other instructions but I have no success to make  this wonderful project working.

**Comment by Shadez** [comment]
This should be fixed after [373] rev. Update, check and please report here.
