### ISSUE TITLE
Talent Calculator does not work

### ISSUE THREAD

**Issue by zogga99** [Shadez/wowarmory#63]
Hi,

in the current version 371 the talent calculator does not work.
The tooltip of all spells is empty and i can't click on one of it.

Screenshot: http://imagr.eu/up/4c76ab26792298_wowarmory.png

Thank you for your great work.
zogga99

**Comment by rbkai** [comment]
confirm for 391 using firefox, but using opera 10.x its working fine, btw: IE 8 wont show the whole page ... what a pity that opera has only 2% marketshare. maybe i will have a look at the java scripts. I'm not too firm in these things but maybe i will have an idea ^^

**Comment by rbkai** [comment]
btw: http://code.google.com/p/xmlarsenal/ on this version talent calculator works fine even in firefox >.< - have checked some files out and it seems that in many cases the code is idendical. maybe its possible to check the javascript from these guy to get it work in this armory here...

**Comment by Shadez** [comment]
Sorry for long response. Talent calculators works perfect with Mozilla Firefox 3.6.9. Try to remove browser cache if you still have problems with it.

**Comment by rbkai** [comment]
found the problem with firefox (and active AdblockPlus):
- http://ads1.msn.com/library/dap.js => while this js is blocked by addblock - the talent calculator doesnt work. youve got an empty tooltip and can not give talentpoints. 
- Do not blocking this js/deactivate addblock  => and talent calc works fine.  
- While delete the js link from /_laouyt/includes.xsl the talent calc also dont work. 
- Why this one is so important that it must be loaded? I
- Is there any way to get talent calk working also with active adblockplus / blocking the ads1.msn.com/library/dap.js?
