### ISSUE TITLE
File Not Found  and  No Search Results errors.

### ISSUE THREAD

**Issue by oszyx329** [Shadez/wowarmory#64]
Hiho. I've installed Shadez-WoWArmory and I have these errors while lf character in it;

File Not Found
This character profile could not be displayed, possibly for one of the following reasons:

```
* The character has been inactive for an extended period of time.
* The character name was spelled incorrectly.
* The profile is temporarily unavailable while the character is in the midst of a process such as a realm transfer or faction change.
* Characters that have been deleted are no longer available on the Armory.
```

Please dont send me back to other thread, there was no response.

My 2 error:

While searching for item or anything i have this error :

No Search Results
Your search did not produce any results. To ensure that you're searching by parameters allowed by the Armory, make sure to:

```
* Only search for the categories currently in the Armory: items, characters, arena teams, guilds, and factions.
* Search by name only.
```

Thanks - please answer.

**Comment by Shadez** [comment]
> Please dont send me back to other thread, there was no response.

Read FAQ section and World of Warcraft Armory thread on GetMangos.com. There WAS response. Please, read carefully.

Your bug is not correct - I dont see any entries from debug log and I can't provide you any help without it. Closed as useless report.

**Comment by oszyx329** [comment]
DEBUG [30-08-2010 15:54:41]: ArmoryDatabaseHandler::_query : unable to execute SQL query (SELECT `gmlevel` FROM `account` WHERE `id`=350 LIMIT 1). MySQL error: none
DEBUG [30-08-2010 15:54:41]: ArmoryDatabaseHandler::_query : unable to execute SQL query (SELECT `gmlevel` FROM `account` WHERE `id`=350 LIMIT 1). MySQL error: none
DEBUG [30-08-2010 15:54:41]: ArmoryDatabaseHandler::_query : unable to execute SQL query (SELECT `guid`, `name`, `class` AS `classId`, `gender` AS `genderId`, `race` AS `raceId`, `level`, `account` FROM `characters` WHERE `name` = 'dexiu'). MySQL error: none
DEBUG [30-08-2010 15:54:41]: ArmoryDatabaseHandler::_query : unable to execute SQL query (SELECT COUNT(`guildid`) FROM `guild` WHERE `name` LIKE '%dexiu%' LIMIT 200). MySQL error: none
DEBUG [30-08-2010 15:54:41]: ArmoryDatabaseHandler::_query : unable to execute SQL query (SELECT COUNT(`arenateamid`) FROM `arena_team` WHERE `name` LIKE '%dexiu%' LIMIT 200). MySQL error: none
ERROR [30-08-2010 15:55:15]: Characters::BuildCharacter : player 1194 (Dexiu) does not have any data in `armory_character_stats` table (SQL update to characters DB not applied?)
ERROR [30-08-2010 15:55:15]: Achievements::CalculateAchievementPoints : player guid not defined
ERROR [30-08-2010 15:55:15]: Achievements::CountCharacterAchievements : player guid not defined
DEBUG [30-08-2010 16:50:16]: ArmoryDatabaseHandler::_query : unable to execute SQL query (SELECT `guid`, `level`, `account` FROM `characters` WHERE `name`='clicker' AND `level` >= 10 LIMIT 200). MySQL error: none
DEBUG [30-08-2010 16:50:16]: ArmoryDatabaseHandler::_query : unable to execute SQL query (SELECT `gmlevel` FROM `account` WHERE `id`=61 LIMIT 1). MySQL error: none
DEBUG [30-08-2010 16:50:16]: ArmoryDatabaseHandler::_query : unable to execute SQL query (SELECT `gmlevel` FROM `account` WHERE `id`=61 LIMIT 1). MySQL error: none
DEBUG [30-08-2010 16:50:16]: ArmoryDatabaseHandler::_query : unable to execute SQL query (SELECT `guid`, `name`, `class` AS `classId`, `gender` AS `genderId`, `race` AS `raceId`, `level`, `account` FROM `characters` WHERE `name` = 'clicker'). MySQL error: none
DEBUG [30-08-2010 16:50:16]: ArmoryDatabaseHandler::_query : unable to execute SQL query (SELECT COUNT(`guildid`) FROM `guild` WHERE `name` LIKE '%clicker%' LIMIT 200). MySQL error: none
DEBUG [30-08-2010 16:50:16]: ArmoryDatabaseHandler::_query : unable to execute SQL query (SELECT COUNT(`arenateamid`) FROM `arena_team` WHERE `name` LIKE '%clicker%' LIMIT 200). MySQL error: none
ERROR [30-08-2010 16:50:43]: Characters::BuildCharacter : player 87 (Clicker) does not have any data in `armory_character_stats` table (SQL update to characters DB not applied?)
ERROR [30-08-2010 16:50:43]: Achievements::CalculateAchievementPoints : player guid not defined
ERROR [30-08-2010 16:50:43]: Achievements::CountCharacterAchievements : player guid not defined
DEBUG [30-08-2010 16:50:49]: ArmoryDatabaseHandler::_query : unable to execute SQL query (SELECT `guid`, `level`, `account` FROM `characters` WHERE `name`='clicker' AND `level` >= 10 LIMIT 200). MySQL error: none
DEBUG [30-08-2010 16:50:49]: ArmoryDatabaseHandler::_query : unable to execute SQL query (SELECT `gmlevel` FROM `account` WHERE `id`=61 LIMIT 1). MySQL error: none
DEBUG [30-08-2010 16:50:49]: ArmoryDatabaseHandler::_query : unable to execute SQL query (SELECT `gmlevel` FROM `account` WHERE `id`=61 LIMIT 1). MySQL error: none
DEBUG [30-08-2010 16:50:49]: ArmoryDatabaseHandler::_query : unable to execute SQL query (SELECT `guid`, `name`, `class` AS `classId`, `gender` AS `genderId`, `race` AS `raceId`, `level`, `account` FROM `characters` WHERE `name` = 'clicker'). MySQL error: none
DEBUG [30-08-2010 16:50:49]: ArmoryDatabaseHandler::_query : unable to execute SQL query (SELECT COUNT(`guildid`) FROM `guild` WHERE `name` LIKE '%clicker%' LIMIT 200). MySQL error: none
DEBUG [30-08-2010 16:50:49]: ArmoryDatabaseHandler::_query : unable to execute SQL query (SELECT COUNT(`arenateamid`) FROM `arena_team` WHERE `name` LIKE '%clicker%' LIMIT 200). MySQL error: none
DEBUG [30-08-2010 16:55:03]: ArmoryDatabaseHandler::_query : unable to execute SQL query (SELECT `guid`, `level`, `account` FROM `characters` WHERE `name`='selenir' AND `level` >= 10 LIMIT 200). MySQL error: none
DEBUG [30-08-2010 16:55:03]: ArmoryDatabaseHandler::_query : unable to execute SQL query (SELECT `gmlevel` FROM `account` WHERE `id`=54 LIMIT 1). MySQL error: none
DEBUG [30-08-2010 16:55:03]: ArmoryDatabaseHandler::_query : unable to execute SQL query (SELECT `gmlevel` FROM `account` WHERE `id`=54 LIMIT 1). MySQL error: none
DEBUG [30-08-2010 16:55:03]: ArmoryDatabaseHandler::_query : unable to execute SQL query (SELECT `guid`, `name`, `class` AS `classId`, `gender` AS `genderId`, `race` AS `raceId`, `level`, `account` FROM `characters` WHERE `name` = 'selenir'). MySQL error: none
DEBUG [30-08-2010 16:55:03]: ArmoryDatabaseHandler::_query : unable to execute SQL query (SELECT COUNT(`guildid`) FROM `guild` WHERE `name` LIKE '%selenir%' LIMIT 200). MySQL error: none
DEBUG [30-08-2010 16:55:03]: ArmoryDatabaseHandler::_query : unable to execute SQL query (SELECT COUNT(`arenateamid`) FROM `arena_team` WHERE `name` LIKE '%selenir%' LIMIT 200). MySQL error: none
ERROR [30-08-2010 16:55:08]: Characters::BuildCharacter : player 66 (Selenir) does not have any data in `armory_character_stats` table (SQL update to characters DB not applied?)
ERROR [30-08-2010 16:55:08]: Achievements::CalculateAchievementPoints : player guid not defined
ERROR [30-08-2010 16:55:08]: Achievements::CountCharacterAchievements : player guid not defined
DEBUG [30-08-2010 16:57:41]: SearchMgr::PerformCharactersSearch : searchQuery not defined
DEBUG [30-08-2010 16:57:54]: SearchMgr::PerformCharactersSearch : searchQuery not defined
DEBUG [30-08-2010 16:58:05]: achievement-firsts.php : realm Darkmoon WoW defined
DEBUG [30-08-2010 16:58:11]: SearchMgr::PerformCharactersSearch : searchQuery not defined

**Comment by Shadez** [comment]
Look at your mysql connection configs. I think they're wrong. Or you're using some unknown emulator (not mangos and not trinity).

**Comment by oszyx329** [comment]
Im using trinity mythcore. Mayby error is here, that didnt clone it, but i downloaded it? Error is here in armory_character_stats. It's not adding to this DB logged characters.

All armory work fine, items search, realm first etc, but errors are in 2v2 tables, 3v3 and 5v5 and displaying character.

**Comment by Shadez** [comment]
> Mayby error is here, that didnt clone it, but i downloaded it?

Have you patched core with wowarmory patches? If no, patch it and compile again.

>  Error is here in armory_character_stats.

Error not only in armory_character_stats table. As you can see in debug log, script can't even request data from `characters` table. Re-check you configs and try to open character page again.

**Comment by oszyx329** [comment]
$ArmoryConfig['multiRealm'][1]['id']                 = 1;
$ArmoryConfig['multiRealm'][1]['name']               = 'XXXXXXX';
$ArmoryConfig['multiRealm'][1]['type']               = 'trinity';
$ArmoryConfig['multiRealm'][1]['host_characters']    = '123123123123';
$ArmoryConfig['multiRealm'][1]['user_characters']    = 'name';
$ArmoryConfig['multiRealm'][1]['pass_characters']    = 'pass';
$ArmoryConfig['multiRealm'][1]['name_characters']    = 'characters';
$ArmoryConfig['multiRealm'][1]['charset_characters'] = 'UTF8';
$ArmoryConfig['multiRealm'][1]['host_world']         = '123123123';
$ArmoryConfig['multiRealm'][1]['user_world']         = 'name';
$ArmoryConfig['multiRealm'][1]['pass_world']         = 'pass';
$ArmoryConfig['multiRealm'][1]['name_world']         = 'world';
$ArmoryConfig['multiRealm'][1]['charset_world']      = 'UTF8';

its my connection config... I've applied all sqls...
