### ISSUE TITLE
386 TrinityCore problems

### ISSUE THREAD

**Issue by Vasago** [Shadez/wowarmory#66]
Arena system has changed error in character-sheet
Arenateams::GetTeamList : unable to get player list for arena team 1934 (Idiots)<br />
<strong>DEBUG</strong> [05-09-2010 13:23:32]: ArmoryDatabaseHandler::_query : unable to execute SQL query (
        SELECT
        `arena_team_member`.`played_season` AS `seasonGamesPlayed`,
        `arena_team_member`.`wons_season` AS `seasonGamesWon`,
        `arena_team_member`.`personal_rating` AS `contribution`,
        `characters`.`guid`,
        `characters`.`name`,
        `characters`.`race` AS `raceId`,
        `characters`.`class` AS `classId`,
        `characters`.`gender` AS `genderId`
        FROM `arena_team_member` AS `arena_team_member`
        LEFT JOIN `characters` AS `characters` ON `characters`.`guid`=`arena_team_member`.`guid`
        WHERE `arena_team_member`.`arenateamid`=1934
        ). MySQL error: none<br 
Here are the changes http://code.google.com/p/trinitycore/source/detail?r=fce5b5c2182cc5c2c53e31d3b082cef11f5811ca

**Comment by Shadez** [comment]
Check after <a href="http://github.com/Shadez/wowarmory/commit/07cbdc6c5526dcb142bb1a47d091ff29b82d2455">[387]</a>, this problem should be fixed.

**Comment by Vasago** [comment]
Problem is with personal rating it is showing incorrect values (much less than it should be) and here are the errors now with latest trinity and revision 389 of armory:
<strong>DEBUG</strong> [11-09-2010 11:52:32]: Arenateams::GetTeamList : unable to get player list for arena team 1136 (XXX)<br />
<strong>DEBUG</strong> [11-09-2010 11:52:33]: ArmoryDatabaseHandler::_query : unable to execute SQL query (SELECT `current_rank` FROM `character_talent` WHERE `guid`=3335 AND `talent_id`=2020 AND `spec`=0). MySQL error: none<br />
<strong>DEBUG</strong> [11-09-2010 11:52:39]: ArmoryDatabaseHandler::_query : unable to execute SQL query (SELECT `gmlevel` FROM `account` WHERE `id`=3453 LIMIT 1). MySQL error: none<br />
<strong>DEBUG</strong> [11-09-2010 11:52:50]: ArmoryDatabaseHandler::_query : unable to execute SQL query (SELECT `name`, `Quality`, `ItemLevel`, `displayid`, `SellPrice`, `BuyPrice`, `Flags2`, `RequiredDisenchantSkill` FROM `item_template` WHERE `entry`=49493 LIMIT 1). MySQL error: none<br />

**Comment by Vasago** [comment]
Arena teams are still chosen incorrectly and members are not really the one listed in armory - in game are different.

**Comment by Vasago** [comment]
Doing new report ...
