### ISSUE TITLE
apply this patch 

### ISSUE THREAD

**Issue by tibirabotto** [Shadez/wowarmory#68]
How do I apply this patch which is in tools / trinity-core?

**Comment by Peshyy** [comment]
in console:
patch -p1 < [NAME_OF_PATCH].patch

**Comment by tibirabotto** [comment]
in that directory I use this command. It runs on windows?

**Comment by Peshyy** [comment]
windows, linux :D

**Comment by tibirabotto** [comment]
ok patch command invalid. Which directory do I put? " the file is in c: / xampp / htdocs / site / tools / trinity core wowarmory_charactes.patch

Windows does not recognize this command patch-p1

**Comment by tortosi** [comment]
these command in windows work perfectly, but the patch are deprecated

**Comment by tibirabotto** [comment]
How do I put the armory to work? because I am ultilizando TrinityCore phaco and when the search

This character profile could not be displayed, possibly for one of the following reasons:

```
* The character has been inactive for an extended period of time.
* The character name was spelled incorrectly.
* The profile is temporarily unavailable while the character is in the midst of a process such as a realm transfer or faction change.
* Characters that have been deleted are no longer available on the Armory.
```

ERROR [12-09-2010 15:15:33]: Characters::BuildCharacter : player 15 (Boromirr) does not have any data in `armory_character_stats` table (SQL update to Characters DB was not applied? / Character was not saved in game? / Server core was not patched?)
ERROR [12-09-2010 15:15:33]: Achievements::InitAchievements : player with guid 0 was not found in `characters` table!

**Comment by Peshyy** [comment]
OK...
Copy the 2 *.patch files from the tools/trinity_core/ folder to the root directory of the TrinityCore scourcecode (The folder you've downloaded TrinityCore)
Linux: Open Terminal (You must have Mercurial/TortoiseHG Installed!!!) and type patch -p1 < [name_of_the_patch].patch
Windows: Start Menu->Run...->cmd->(You must have Mercurial/TortoiseHG Installed)[path_to_YOUR_ROOT_sourcecode_folder]->patch -p1 < [name_of_the_patch].patch

After that compile
Make a new DB called 'armory' and import the SQL file+updates from the sql/ folder in the armory folder
Import 'characters_patch.sql' from tools/trinity_core/sql/ folder to your characters database(s)
Configure Armory
Login with a character, wait five minutes, logout, open armory in browser and ta-da! :D

**Comment by tibirabotto** [comment]
sorry. you have any screenshot or video link to help me?

**Comment by Peshyy** [comment]
I'm sorry too, but I don't have and I don't want to do :D:D:D
Did you read the INSTALL.file??

**Comment by tibirabotto** [comment]
I installed mercurial and TortoiseHG, I use the core PryDevSer. I put the files. Patch folder within the core and along with world.exe relamd.exe, I ate at the command line is where the files .*. PATCH ultiliza patch-p 1 <wowarmory.characters.patch and get an answer windows saying that patch is not a valid command.

**Comment by Peshyy** [comment]
it's patch -p1 NOT patch- p 1 !

**Comment by Peshyy** [comment]
patch [space] -p1 [space] < [space] wowarmory_*.patch

**Comment by tibirabotto** [comment]
patch [space] -p1 [space] < [space] wowarmory_*.patch anyway that was put, like using the google translator to talk to you he must have joined :D

**Comment by tortosi** [comment]
I aply the patch after o before cmake??

**Comment by tibirabotto** [comment]
No. I installed cmake on windows now. how do I use?

WHERE to build source code (Which way do I put here?)

WHERE to build binaries (Which way do I put here?)

I am very grateful for the help.

**Comment by Shadez** [comment]
Closed as non-related to Armory. Read the forums about patches applying.
