### ISSUE TITLE
XML parsing error

### ISSUE THREAD

**Issue by ghost** [Shadez/wowarmory#69]
Hi shadez,
i have error with xml parsing error.
I dont know can i fix this problem. Can you help me ?
Here is problem:
XML Parsing Error: syntax error
Location: http://altron-wow.eu/armory/character-sheet.xml?r=Pixie&cn=Qili
Line Number 2, Column 1:Warning: Invalid argument supplied for foreach() in /httpd/html/altron_woweu/www/armory/character-sheet.php on line 146
^

I read other issues, but i not found F.A.Q.
thanks you very much

**Comment by dgoujard** [comment]
i have also this error with some request.
