### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by ondrejbudai** [Shadez/wowarmory#7]
Hello,
if I search for any name, armory gives me results, but if I open someone's profile, armory gives me this error:

File Not Found
This character profile could not be displayed, possibly for one of the following reasons:
The character has been inactive for an extended period of time.
The character name was spelled incorrectly.
The profile is temporarily unavailable while the character is in the midst of a process such as a realm transfer or faction change.
Characters that have been deleted are no longer available on the Armory.

**Comment by Shadez** [comment]
Have you applied wowarmory patch to MaNGOS core and characters DB?

**Comment by sprokopiev** [comment]
i have applied wowarmory patch for trinitycore and all sql file to my database and still nothing.Error : File Not Found

**Comment by Shadez** [comment]
Read F.A.Q. section in project thread on getmangos.com and post error log here.
