### ISSUE TITLE
FreeBSD compile error

### ISSUE THREAD

**Issue by sprokopiev** [Shadez/wowarmory#70]
i have a problem with trinitycore patch.
after applying wowarmory_patch.patch and wowarena......patch

[ 15%] Building CXX object src/server/game/CMakeFiles/game.dir/Battlegrounds/Battleground.cpp.o
/usr/home/darkvader/install/trinitycore/src/server/game/Battlegrounds/Battleground.cpp: In member function 'virtual void Battleground::UpdatePlayerScore(Player_, uint32, uint32, bool)':
/usr/home/darkvader/install/trinitycore/src/server/game/Battlegrounds/Battleground.cpp:1352: error: 'SCORE_DAMAGE_TAKEN' was not declared in this scope
/usr/home/darkvader/install/trinitycore/src/server/game/Battlegrounds/Battleground.cpp:1353: error: 'class BattlegroundScore' has no member named 'DamageTaken'
/usr/home/darkvader/install/trinitycore/src/server/game/Battlegrounds/Battleground.cpp:1355: error: 'SCORE_HEALING_TAKEN' was not declared in this scope
/usr/home/darkvader/install/trinitycore/src/server/game/Battlegrounds/Battleground.cpp:1356: error: 'class BattlegroundScore' has no member named 'HealingTaken'
gmake[2]: *_\* [src/server/game/CMakeFiles/game.dir/Battlegrounds/Battleground.cpp.o] Error 1
gmake[1]: **\* [src/server/game/CMakeFiles/game.dir/all] Error 2
gmake: **\* [all] Error 2

**Comment by burnham** [comment]
Fix the patch in the right way and check, ass soon you do it come back here and say "is resolve" then is easy close this issue.
