### ISSUE TITLE
Missing argument in function

### ISSUE THREAD

**Issue by shockwave** [Shadez/wowarmory#72]
Hi , I report to you an issue , whith the last rev you can't display the character profile (item,achievement etc..) , there is an error :

<b>Warning</b>:  Missing argument 1 for Achievements::Achievements(), called in /var/www/armory/wowarmory/includes/classes/class.characters.php on line 696 and defined in <b>/var/www/armory/wowarmory/includes/classes/class.achievements.php</b> on line <b>64</b><br />

**Comment by Shadez** [comment]
Match <b>includes/armory_loader.php</b> file with this file on GitHub. Proper argument should be send on class initialization ($characters = new Characters($armory);)
