### ISSUE TITLE
Error on Showing Chars or Guilds

### ISSUE THREAD

**Issue by Cartman87** [Shadez/wowarmory#74]
<b>Warning</b>:  Missing argument 1 for Achievements::Achievements(), called in /var/www/vhosts/inferno-wow.de/subdomains/armory/httpdocs/includes/classes/class.characters.php on line 696 and defined in <b>/var/www/vhosts/inferno-wow.de/subdomains/armory/httpdocs/includes/classes/class.achievements.php</b> on line <b>64</b><br />
^

or 

<b>Warning</b>:  Missing argument 1 for Characters::Characters(), called in /var/www/vhosts/inferno-wow.de/subdomains/armory/httpdocs/includes/classes/class.guilds.php on line 209 and defined in <b>/var/www/vhosts/inferno-wow.de/subdomains/armory/httpdocs/includes/classes/class.characters.php</b> on line <b>244</b><br />
^

**Comment by samalex** [comment]
The same problem.

**Comment by Shadez** [comment]
Fixed, thanks for reports.
Closed.
