### ISSUE TITLE
Armory is wrong 

### ISSUE THREAD

**Issue by calvo** [Shadez/wowarmory#76]
Hi, i install armory in http://lostworld.es/armeria/ is erros is no found charactecters items and guild 
help 

http://lostworld.es/armeria/search.xml?searchQuery=calvo&searchType=all pj is create 

wrong is http://lostworld.es/armeria/character-sheet.xml?r=Armory+Realm+2&cn=Calvo 

Help plz

**Comment by Shadez** [comment]
Closed as uninformative. Please, read your debug log and copy-paste related to your problem errors into new issue. Thank you.

**Comment by calvo** [comment]
<strong>DEBUG</strong> [16-11-2010 21:12:33]: ArmoryDatabaseHandler::_query : unable to execute SQL query (SELECT 
        `item_template`.`entry` AS `id`,
        `item_template`.`name`,
        `item_template`.`ItemLevel`,
        `item_template`.`Quality` AS `rarity`, 
        `item_template`.`displayid`, 
        `item_template`.`bonding`, 
        `item_template`.`flags`, 
        `item_template`.`duration`
            FROM `item_template` WHERE (`item_template`.`class`='4') ORDER BY `item_template`.`ItemLevel` DESC LIMIT 200). MySQL error: none<br />
<strong>ERROR</strong> [16-11-2010 21:12:33]: SearchMgr::PerformAdvancedItemsSearch : unable to execute SQL query "SELECT 
        `item_template`.`entry` AS `id`,
        `item_template`.`name`,
        `item_template`.`ItemLevel`,
        `item_template`.`Quality` AS `rarity`, 
        `item_template`.`displayid`, 
        `item_template`.`bonding`, 
        `item_template`.`flags`, 
        `item_template`.`duration` 

is error sql to correct?

**Comment by calvo** [comment]
db ytdb 572 trinity core
