### ISSUE TITLE
Compile errors with TC rev

### ISSUE THREAD

**Issue by ArcAIN6** [Shadez/wowarmory#79]
Seems there is something wrong with the armory patch (armory_arena had hunkfails so reverted and only applied armory patch)

Could you possibly edit the source to fix this, and perhaps explain the change here, that way i can just fix the files manually instead of reverting, and re-patching.

Thanks

Error output:

[ 23%] Building CXX object src/server/game/CMakeFiles/game.dir/Entities/Player/Player.cpp.o
/home/trinity/trinitycore/src/server/game/Entities/Player/Player.cpp: In member function â€˜void Player::WriteWowArmoryDatabaseLog(uint32, uint32)â€™:
/home/trinity/trinitycore/src/server/game/Entities/Player/Player.cpp:24354: error: â€˜QueryResult_AutoPtrâ€™ was not declared in this scope
/home/trinity/trinitycore/src/server/game/Entities/Player/Player.cpp:24354: error: expected `;' before â€˜resultâ€™
/home/trinity/trinitycore/src/server/game/Entities/Player/Player.cpp:24355: error: â€˜resultâ€™ was not declared in this scope
make[2]: **\* [src/server/game/CMakeFiles/game.dir/Entities/Player/Player.cpp.o] Error 1
make[1]: **\* [src/server/game/CMakeFiles/game.dir/all] Error 2
make: **\* [all] Error 2

**Comment by ArcAIN6** [comment]
sorry.. forgot to add the rev number in title... it's TC rev 10101

**Comment by Drethek** [comment]
Change QueryResult_AutoPtr with QueryResult

**Comment by ArcAIN6** [comment]
tyvm :D
