### ISSUE TITLE
Trinitycore 3.3.3a + .patch + sqls 

### ISSUE THREAD

**Issue by Gomez22** [Shadez/wowarmory#8]
I try your armory and get this error alot, when I try to view a char profile or in some pages and arena team top show nothing

Warning: mysql_errno(): supplied argument is not a valid MySQL-Link resource in /home/a77366812/domains/mydomainhere.com/public_html/armory/includes/classes/libs/DbSimple/Mysql.php  on line 184

and 

Warning: mysql_real_escape_string() expects parameter 2 to be resource, boolean given in /home/a77366812/domains/mydomainhere.com/public_html/armory/includes/classes/libs/DbSimple/Mysql.php  on line 58

Warning: Cannot modify header information - headers already sent by (output started at /home/a77366812/domains/mydomainhere.com/public_html/armory/includes/classes/libs/DbSimple/Mysql.php:184) in /home/a77366812/domains/mydomainhere.com/public_html/armory/character-sheet.php  on line 34

**Comment by Gomez22** [comment]
After 24h I don`t get any errors from above, just this when I try to see profile, arena top still empty

 Profile Page
     Armory
    Error Encountered

File Not Found
This character profile could not be displayed, possibly for one of the following reasons:

```
* The character has been inactive for an extended period of time.
* The character name was spelled incorrectly.
* The profile is temporarily unavailable while the character is in the midst of a process such as a realm transfer or faction change.
* Characters that have been deleted are no longer available on the Armory.
```

Arena top - empty

Achievement Firsts 
An Error has Occured.
Please try a new query.

**Comment by gyullo** [comment]
The same problem here, Characters profile error.
I solved the arena ladder problem, but i couldnt find the profile problem, but i can said that appear after REV:194 i dont know in which specifically but in 193 work perfect (i use 193 with some modified for trinity, when i update all with your work problem appear)

**Comment by Shadez** [comment]
> The same problem here, Characters profile error.

Try this: http://github.com/Shadez/wowarmory/commit/383e48cf09e1c208704735a1e316c8452e3297ed

**Comment by Vasago** [comment]
After updating to 207 error still exists:
File Not Found
This character profile could not be displayed, possibly for one of the following reasons:

```
* The character has been inactive for an extended period of time.
* The character name was spelled incorrectly.
* The profile is temporarily unavailable while the character is in the midst of a process such as a realm transfer or faction change.
* Characters that have been deleted are no longer available on the Armory.
```

**Comment by Vasago** [comment]
amsjunior1: How did you make pictures visible? It doesnt work for me: http://github.com/Shadez/wowarmory/issues#issue/11

**Comment by Shadez** [comment]
> After updating to 207 error still exists:

Update to 208 rev., change $ArmoryConfig['settings']['useDebug'] to true, $ArmoryConfig['settings']['logLevel'] to 2 and open character-sheet page. Then show me your log (http://armory_url/cache/_debug/index.php) and your configuration.php
Please, use http://paste2.org/ for files content.

**Comment by Shadez** [comment]
Update to [209] and test again ;)

**Comment by Shadez** [comment]
> more error....

It's not errors, just debug ouptus.
About this:

> Characters::GetCharacterItemInfo : unable to get item_id for player 70 (Trautman); slotid is head

have you applied Trinity core patch and SQL update to characters DB (from tools/trinity_core folder)?

**Comment by Shadez** [comment]
This patch is very important part - without it Armory can't work.
Please, read all INSTALL steps and make sure thar you've done all of them and only after it post any bugreports.
Thanks.

**Comment by Vasago** [comment]
http://paste2.org/p/851826 - here is mine 
player 30941 (Igeto) does not have any data in `armory_character_stats` table (SQL update to characters DB not applied?)
There are really non data of this character but there are many others ... when are the character data written to this table for all characters not only some?

**Comment by Vasago** [comment]
BTW problem with layout still exists - can you add degub to main page pictures or something to find out why it does not appear? http://github.com/Shadez/wowarmory/issues#issue/11 Thx

**Comment by Shadez** [comment]
> There are really non data of this character but there are many others ... when are the character data written to this table for all characters not only some?

Read INSTALL file, please.

> BTW problem with layout still exists - can you add degub to main page pictures or something to find out why it does not appear?

I'll see this later (haven't enough time right now :( )

**Comment by Vasago** [comment]
In INSTALL file there is nothing about why there are only some of the characters and not all and when they will be there and how often is the update ...

**Comment by Shadez** [comment]
If you've patched core, data will be added in DB at every character save.

> why there are only some of the characters

May be this data from old core and your current is not patched?

**Comment by amsjunior1** [comment]
update revision 212.

http://paste2.org/p/852792

**Comment by Shadez** [comment]
And what's the error now? I don't see any bad lines in log (GetItemInfo errors may be caused because character doesn't have items on selected gear slots)

**Comment by amsjunior1** [comment]
model view dont work

loading is freeze like 20% and dont show model.

calendar give me this message
Error
A character must be recently active, on an account in good standing, on a European realm, and be at least level 10 to appear on a calendar.
error our db no save data?

**Comment by Vasago** [comment]
I dont have problem with loading models but some textures of new items are missing - will there be any update of it and when? THX

**Comment by amsjunior1** [comment]
give me one photo your model working......please

**Comment by Vasago** [comment]
When i say it is working it is working :-P
http://yfrog.com/2hmodeltp

But some new textures of new items are missing and i am curious when they can be available.

BTW stats are handled in bad way - HP and mana are also included buffs which should not (just base stats) and Spell Power is also wrong displayed. Thx for this project.

**Comment by Gomez22** [comment]
How did you "fix" 3d view ? // on my server or is freeze at 20% - 60%  // or is loading with nothing to show just some arrows and tools to control the image from flash.

I put models folder in root folder, there where index.php is

**Comment by Vasago** [comment]
I do not know i just copied the files and folders from the link from txt file and that was it :-)

I am interesteds how can i add to armory people who did not join to game and not had save process is there any to add them manually all? .save all command doesnt work

**Comment by Shadez** [comment]
> I am interesteds how can i add to armory people who did not join to game and not had save process is there any to add them manually all?

The only way is log in and .save.
`.save all` command saves only currenly online players.

**Comment by Matt-One** [comment]
How to solve this error? i got rev 226 with sql and patch correctly installed. when u search for a player this error show up. :/ (i use Firefox)

XML error interpretation: illegal content after the element
Address: http://pandewow.hopto.org/wowarmory/search.xml?searchQuery=angel&searchType=all
Linea numero 2, colonna 1:

<b>Warning</b>:  mysql_errno(): supplied argument is not a valid MySQL-Link resource in <b>/var/www/vhosts/default/htdocs/wowarmory/includes/classes/libs/DbSimple/Mysql.php</b> on line <b>184</b><br />
^

**Comment by Shadez** [comment]
Check MySQL connection info in configuration.php

**Comment by Matt-One** [comment]
i checked my configuration file and it's ok......what could be? Item Works....i can list all the items in the armory. i'm asking myself...but i have to configure the first part of Multirealm if i have only one realm?

**Comment by Gomez22** [comment]
Same as Matt-One is random, some time after more refresh works, sometimes take hours... to function again

**Comment by Matt-One** [comment]
for me it never worked for days...always the same error...can somebody tell me if i have to modify the address into the first part of multirealm? i use only one realm...

**Comment by Gomez22** [comment]
lots of errors like this, debug log is quite big, you have here few lines

http://paste2.org/p/864427

**Comment by gyullo** [comment]
i cant reproduce the errors posted above. Work perfect to me

**Comment by Shadez** [comment]
_removed_

**Comment by Shadez** [comment]
As far as i know, problem was solved by correct armory configuring. Closed.
