### ISSUE TITLE
armory_patch_for_trinitycore_rev10329

### ISSUE THREAD

**Issue by burnham** [Shadez/wowarmory#89]
Hi people, just to contribute a bit with the community I had update patch for amory.
http://pastebin.com/4Vc2Eaix
I hope to save you a bit of work and enjoy with it
http://armeria.adictoswow.com/
http://armeria.adictoswow.com/character-sheet.xml?r=AdictosWoW+3.3.5a&cn=Mean

**Comment by gen1us2k** [comment]
This patches crashes server..

**Comment by burnham** [comment]
lonk crash log.
