### ISSUE TITLE
characters_feed_log table

### ISSUE THREAD

**Issue by burnham** [Shadez/wowarmory#90]
characters_feed_log, table is not recording data.

**Comment by Misimouse** [comment]
Do you applier the patch?

**Comment by burnham** [comment]
Amigo, estoy reportando que no se guardan los datos en dicha tabla, nosotros si tenemos aplicado el parche.

**Comment by calvo** [comment]
Bunaran nesesito tu ayuda plz mi msn germanparapente@hotmail.com

**Comment by burnham** [comment]
Hola German, dime en que puedo ayudarte?

**Comment by calvo** [comment]
mira es yo ya tengo el parche que del core funciona bastante bien en la rev de 1450 creo y funciona bastante pero la armeria no le funciona la base de datos de los items y me saka un error sabes? como puedo hacer que funcione? los personajes 3D sirven etc... pero no sirve eso aca te dejo link http://armeria.lostworld.es/
