### ISSUE TITLE
Trinity core change scrtucture

### ISSUE THREAD

**Issue by calvo** [Shadez/wowarmory#99]
hi Trinity core change estructure in item_template 

change http://code.google.com/p/trinitycore/source/detail?r=022f3858fc4990ebd7b315d29ca85a368c40a33d 

Debug ]:
<strong>DEBUG</strong> [18-12-2010 01:23:08]: ArmoryDatabaseHandler::_query : unable to execute SQL query (SELECT `item`, `slot`, `item_template`, `bag` FROM `character_inventory` WHERE `bag` = 0 AND `slot` < 19 AND `guid` = 847). MySQL error: "Unknown column 'item_template' in 'field list'" (Error #1054)<br />
<strong>DEBUG</strong> [18-12-2010 01:23:08]:

**Comment by Shadez** [comment]
Check after <a href="http://github.com/Shadez/wowarmory/commit/a65b527c644ae60bfa7d75e7b3fe4a487de445e4">[419] commit</a>.
Thank you!

**Comment by calvo** [comment]
hi, tnx for fix, wrong is http://armeria.lostworld.es/character-sheet.xml?r=Exodar&cn=Calvo does not display items
